# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
// // // // // // // // // // // // // //
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class LogLevel(Enum):
    """
    日誌層級 (已擴展為標準 syslog 七級規範)
    """
    DEBUG = 0
    INFO = 1
    WARN = 2
    ERROR = 3
    CRIT = 4
    ALERT = 5
    EMERG = 6

@dataclass
class LogEntry:
    """
    定義解析後的結構化日誌紀錄
    """
    timestamp: str
    level: LogLevel
    message: str
    tags: List[Tuple[str, str]]


@dataclass
class ParseError_InvalidFormat:
    value: str


@dataclass
class ParseError_UnsupportedVersion:
    value: int


@dataclass
class ParseError_CorruptedData:
    pass


ParseError = Union[ParseError_InvalidFormat, ParseError_UnsupportedVersion, ParseError_CorruptedData]
"""
解析錯誤的類型
"""



