// Code generated by wit-bindgen-go. DO NOT EDIT.

package formatplugin

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "local:log-process/format-plugin@0.1.0".
var Exports struct {
	// Format represents the caller-defined, exported function "format".
	//
	//	format: func(struct-data: list<log-entry>) -> result<list<list<u8>>, plugin-error>
	Format func(structData cm.List[LogEntry]) (result cm.Result[PluginErrorShape, cm.List[cm.List[uint8]], PluginError])

	// ReportUsage represents the caller-defined, exported function "report-usage".
	//
	//	report-usage: func() -> u64
	ReportUsage func() (result uint64)
}
