// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package formatplugin represents the world "local:log-process/format-plugin@0.1.0".
//
// ─────────────────────────────────────────────
// format-plugin
// ─────────────────────────────────────────────
package formatplugin

import (
	pipelineprocess "example.com/internal/local/log-process/pipeline-process"
)

// LogEntry represents the type alias "local:log-process/format-plugin@0.1.0#log-entry".
//
// See [pipelineprocess.LogEntry] for more information.
type LogEntry = pipelineprocess.LogEntry

// PluginError represents the type alias "local:log-process/format-plugin@0.1.0#plugin-error".
//
// See [pipelineprocess.PluginError] for more information.
type PluginError = pipelineprocess.PluginError
