// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;

namespace ParserPluginWorld.wit.Imports.wasi.cli.v0_2_0
{
    public static class TerminalStdoutImportsInterop {

        public static class GetTerminalStdoutWasmInterop
        {
            [global::System.Runtime.InteropServices.DllImportAttribute("wasi:cli/terminal-stdout@0.2.0", EntryPoint = "get-terminal-stdout"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
            public static extern void wasmImportGetTerminalStdout(nint p0);
        }

    }
}
