// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0;

public interface IUdpImports {

    public struct IncomingDatagram {
        public byte[] data;
        public global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress remoteAddress;

        public IncomingDatagram(byte[] data, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress remoteAddress) {
            this.data = data;
            this.remoteAddress = remoteAddress;
        }
    }

    public struct OutgoingDatagram {
        public byte[] data;
        public global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress? remoteAddress;

        public OutgoingDatagram(byte[] data, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress? remoteAddress) {
            this.data = data;
            this.remoteAddress = remoteAddress;
        }
    }

    public class UdpSocket: global::System.IDisposable {
        internal int Handle { get; set; }

        public readonly record struct THandle(int Handle);

        public UdpSocket(THandle handle) {
            Handle = handle.Handle;
        }

        public void Dispose() {
            Dispose(true);
        }

        [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[resource-drop]udp-socket"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
        private static extern void wasmImportResourceDrop(int p0);

        protected virtual void Dispose(bool disposing) {
            if (disposing && Handle != 0) {
                wasmImportResourceDrop(Handle);
                Handle = 0;
            }
        }

        public  unsafe void StartBind(global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Network network, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress localAddress)
        {
            var handle = this.Handle;
            var handle0 = network.Handle;

            int lowered;
            int lowered4;
            int lowered5;
            int lowered6;
            int lowered7;
            int lowered8;
            int lowered9;
            int lowered10;
            int lowered11;
            int lowered12;
            int lowered13;
            int lowered14;

            switch (localAddress.Tag) {
                case 0: {
                    global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv4SocketAddress payload = localAddress.AsIpv4;

                    lowered = 0;
                    lowered4 = payload.port;
                    lowered5 = payload.address.Item1;
                    lowered6 = payload.address.Item2;
                    lowered7 = payload.address.Item3;
                    lowered8 = payload.address.Item4;
                    lowered9 = 0;
                    lowered10 = 0;
                    lowered11 = 0;
                    lowered12 = 0;
                    lowered13 = 0;
                    lowered14 = 0;

                    break;
                }
                case 1: {
                    global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv6SocketAddress payload3 = localAddress.AsIpv6;

                    lowered = 1;
                    lowered4 = payload3.port;
                    lowered5 = unchecked((int)(payload3.flowInfo));
                    lowered6 = payload3.address.Item1;
                    lowered7 = payload3.address.Item2;
                    lowered8 = payload3.address.Item3;
                    lowered9 = payload3.address.Item4;
                    lowered10 = payload3.address.Item5;
                    lowered11 = payload3.address.Item6;
                    lowered12 = payload3.address.Item7;
                    lowered13 = payload3.address.Item8;
                    lowered14 = unchecked((int)(payload3.scopeId));

                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant: " + localAddress);
            }

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            UdpImportsInterop.UdpSocket.StartBindWasmInterop.wasmImportStartBind(handle, handle0, lowered, lowered4, lowered5, lowered6, lowered7, lowered8, lowered9, lowered10, lowered11, lowered12, lowered13, lowered14, ptr);

            Result<None, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<None, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(new global::ParserPluginWorld.None());
                    break;
                }
                case 1: {

                    lifted = Result<None, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe void FinishBind()
        {
            var handle = this.Handle;

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            UdpImportsInterop.UdpSocket.FinishBindWasmInterop.wasmImportFinishBind(handle, ptr);

            Result<None, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<None, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(new global::ParserPluginWorld.None());
                    break;
                }
                case 1: {

                    lifted = Result<None, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe (global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.IncomingDatagramStream, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.OutgoingDatagramStream) Stream(global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress? remoteAddress)
        {
            var handle = this.Handle;

            int lowered20;
            int lowered21;
            int lowered22;
            int lowered23;
            int lowered24;
            int lowered25;
            int lowered26;
            int lowered27;
            int lowered28;
            int lowered29;
            int lowered30;
            int lowered31;
            int lowered32;

            if (remoteAddress != null) {
                var payload2 = (global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress) remoteAddress;

                int lowered;
                int lowered9;
                int lowered10;
                int lowered11;
                int lowered12;
                int lowered13;
                int lowered14;
                int lowered15;
                int lowered16;
                int lowered17;
                int lowered18;
                int lowered19;

                switch (payload2.Tag) {
                    case 0: {
                        global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv4SocketAddress payload5 = payload2.AsIpv4;

                        lowered = 0;
                        lowered9 = payload5.port;
                        lowered10 = payload5.address.Item1;
                        lowered11 = payload5.address.Item2;
                        lowered12 = payload5.address.Item3;
                        lowered13 = payload5.address.Item4;
                        lowered14 = 0;
                        lowered15 = 0;
                        lowered16 = 0;
                        lowered17 = 0;
                        lowered18 = 0;
                        lowered19 = 0;

                        break;
                    }
                    case 1: {
                        global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv6SocketAddress payload8 = payload2.AsIpv6;

                        lowered = 1;
                        lowered9 = payload8.port;
                        lowered10 = unchecked((int)(payload8.flowInfo));
                        lowered11 = payload8.address.Item1;
                        lowered12 = payload8.address.Item2;
                        lowered13 = payload8.address.Item3;
                        lowered14 = payload8.address.Item4;
                        lowered15 = payload8.address.Item5;
                        lowered16 = payload8.address.Item6;
                        lowered17 = payload8.address.Item7;
                        lowered18 = payload8.address.Item8;
                        lowered19 = unchecked((int)(payload8.scopeId));

                        break;
                    }

                    default: throw new global::System.ArgumentException("invalid discriminant: " + payload2);
                }

                lowered20 = 1;
                lowered21 = lowered;
                lowered22 = lowered9;
                lowered23 = lowered10;
                lowered24 = lowered11;
                lowered25 = lowered12;
                lowered26 = lowered13;
                lowered27 = lowered14;
                lowered28 = lowered15;
                lowered29 = lowered16;
                lowered30 = lowered17;
                lowered31 = lowered18;
                lowered32 = lowered19;

            } else {

                lowered20 = 0;
                lowered21 = 0;
                lowered22 = 0;
                lowered23 = 0;
                lowered24 = 0;
                lowered25 = 0;
                lowered26 = 0;
                lowered27 = 0;
                lowered28 = 0;
                lowered29 = 0;
                lowered30 = 0;
                lowered31 = 0;
                lowered32 = 0;

            }

            var retArea = stackalloc uint[4];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
            UdpImportsInterop.UdpSocket.StreamWasmInterop.wasmImportStream(handle, lowered20, lowered21, lowered22, lowered23, lowered24, lowered25, lowered26, lowered27, lowered28, lowered29, lowered30, lowered31, lowered32, ptr);

            Result<(global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.IncomingDatagramStream, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.OutgoingDatagramStream), global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {
                    var resource = new global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.IncomingDatagramStream(new global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.IncomingDatagramStream.THandle(new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0]));
                    var resource35 = new global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.OutgoingDatagramStream(new global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.OutgoingDatagramStream.THandle(new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]));

                    lifted = Result<(global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.IncomingDatagramStream, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.OutgoingDatagramStream), global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok((resource, resource35));
                    break;
                }
                case 1: {

                    lifted = Result<(global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.IncomingDatagramStream, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.OutgoingDatagramStream), global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress LocalAddress()
        {
            var handle = this.Handle;

            var retArea = stackalloc uint[10];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
            UdpImportsInterop.UdpSocket.LocalAddressWasmInterop.wasmImportLocalAddress(handle, ptr);

            Result<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted6;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress lifted;

                    switch (new global::System.Span<byte>((byte*)ptr + 4, 1)[0]) {
                        case 0: {

                            lifted = global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress.Ipv4(new global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv4SocketAddress (
                            ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 8), 1)[0]), (((byte)new global::System.Span<byte>((byte*)ptr + 10, 1)[0]), ((byte)new global::System.Span<byte>((byte*)ptr + 11, 1)[0]), ((byte)new global::System.Span<byte>((byte*)ptr + 12, 1)[0]), ((byte)new global::System.Span<byte>((byte*)ptr + 13, 1)[0]))));
                            break;
                        }
                        case 1: {

                            lifted = global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress.Ipv6(new global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv6SocketAddress (
                            ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 8), 1)[0]), unchecked((uint)(new global::System.Span<int>((void*)((byte*)ptr + 12), 1)[0])), (((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 16), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 18), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 20), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 22), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 24), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 26), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 28), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 30), 1)[0])), unchecked((uint)(new global::System.Span<int>((void*)((byte*)ptr + 32), 1)[0]))));
                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    }

                    lifted6 = Result<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(lifted);
                    break;
                }
                case 1: {

                    lifted6 = Result<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted6.IsOk)
            {
                var tmp = lifted6.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted6.AsErr!, 0);
            }

        }

        public  unsafe global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress RemoteAddress()
        {
            var handle = this.Handle;

            var retArea = stackalloc uint[10];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
            UdpImportsInterop.UdpSocket.RemoteAddressWasmInterop.wasmImportRemoteAddress(handle, ptr);

            Result<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted6;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress lifted;

                    switch (new global::System.Span<byte>((byte*)ptr + 4, 1)[0]) {
                        case 0: {

                            lifted = global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress.Ipv4(new global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv4SocketAddress (
                            ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 8), 1)[0]), (((byte)new global::System.Span<byte>((byte*)ptr + 10, 1)[0]), ((byte)new global::System.Span<byte>((byte*)ptr + 11, 1)[0]), ((byte)new global::System.Span<byte>((byte*)ptr + 12, 1)[0]), ((byte)new global::System.Span<byte>((byte*)ptr + 13, 1)[0]))));
                            break;
                        }
                        case 1: {

                            lifted = global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress.Ipv6(new global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv6SocketAddress (
                            ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 8), 1)[0]), unchecked((uint)(new global::System.Span<int>((void*)((byte*)ptr + 12), 1)[0])), (((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 16), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 18), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 20), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 22), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 24), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 26), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 28), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 30), 1)[0])), unchecked((uint)(new global::System.Span<int>((void*)((byte*)ptr + 32), 1)[0]))));
                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    }

                    lifted6 = Result<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(lifted);
                    break;
                }
                case 1: {

                    lifted6 = Result<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted6.IsOk)
            {
                var tmp = lifted6.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted6.AsErr!, 0);
            }

        }

        public  unsafe global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpAddressFamily AddressFamily()
        {
            var handle = this.Handle;
            var result =  UdpImportsInterop.UdpSocket.AddressFamilyWasmInterop.wasmImportAddressFamily(handle);
            return (global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpAddressFamily)result;

        }

        public  unsafe byte UnicastHopLimit()
        {
            var handle = this.Handle;

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            UdpImportsInterop.UdpSocket.UnicastHopLimitWasmInterop.wasmImportUnicastHopLimit(handle, ptr);

            Result<byte, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<byte, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(((byte)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]));
                    break;
                }
                case 1: {

                    lifted = Result<byte, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe void SetUnicastHopLimit(byte value)
        {
            var handle = this.Handle;

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            UdpImportsInterop.UdpSocket.SetUnicastHopLimitWasmInterop.wasmImportSetUnicastHopLimit(handle, value, ptr);

            Result<None, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<None, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(new global::ParserPluginWorld.None());
                    break;
                }
                case 1: {

                    lifted = Result<None, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe ulong ReceiveBufferSize()
        {
            var handle = this.Handle;

            var retArea = stackalloc ulong[3];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 8);
            UdpImportsInterop.UdpSocket.ReceiveBufferSizeWasmInterop.wasmImportReceiveBufferSize(handle, ptr);

            Result<ulong, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<ulong, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(unchecked((ulong)(new global::System.Span<long>((void*)((byte*)ptr + 8), 1)[0])));
                    break;
                }
                case 1: {

                    lifted = Result<ulong, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 8, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe void SetReceiveBufferSize(ulong value)
        {
            var handle = this.Handle;

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            UdpImportsInterop.UdpSocket.SetReceiveBufferSizeWasmInterop.wasmImportSetReceiveBufferSize(handle, unchecked((long)(value)), ptr);

            Result<None, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<None, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(new global::ParserPluginWorld.None());
                    break;
                }
                case 1: {

                    lifted = Result<None, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe ulong SendBufferSize()
        {
            var handle = this.Handle;

            var retArea = stackalloc ulong[3];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 8);
            UdpImportsInterop.UdpSocket.SendBufferSizeWasmInterop.wasmImportSendBufferSize(handle, ptr);

            Result<ulong, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<ulong, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(unchecked((ulong)(new global::System.Span<long>((void*)((byte*)ptr + 8), 1)[0])));
                    break;
                }
                case 1: {

                    lifted = Result<ulong, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 8, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe void SetSendBufferSize(ulong value)
        {
            var handle = this.Handle;

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            UdpImportsInterop.UdpSocket.SetSendBufferSizeWasmInterop.wasmImportSetSendBufferSize(handle, unchecked((long)(value)), ptr);

            Result<None, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<None, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(new global::ParserPluginWorld.None());
                    break;
                }
                case 1: {

                    lifted = Result<None, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe global::ParserPluginWorld.wit.Imports.wasi.io.v0_2_0.IPollImports.Pollable Subscribe()
        {
            var handle = this.Handle;
            var result =  UdpImportsInterop.UdpSocket.SubscribeWasmInterop.wasmImportSubscribe(handle);
            var resource = new global::ParserPluginWorld.wit.Imports.wasi.io.v0_2_0.IPollImports.Pollable(new global::ParserPluginWorld.wit.Imports.wasi.io.v0_2_0.IPollImports.Pollable.THandle(result));
            return resource;

        }

    }

    public class IncomingDatagramStream: global::System.IDisposable {
        internal int Handle { get; set; }

        public readonly record struct THandle(int Handle);

        public IncomingDatagramStream(THandle handle) {
            Handle = handle.Handle;
        }

        public void Dispose() {
            Dispose(true);
        }

        [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[resource-drop]incoming-datagram-stream"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
        private static extern void wasmImportResourceDrop(int p0);

        protected virtual void Dispose(bool disposing) {
            if (disposing && Handle != 0) {
                wasmImportResourceDrop(Handle);
                Handle = 0;
            }
        }

        public  unsafe global::System.Collections.Generic.List<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.IncomingDatagram> Receive(ulong maxResults)
        {
            var handle = this.Handle;

            var retArea = stackalloc uint[4];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
            UdpImportsInterop.IncomingDatagramStream.ReceiveWasmInterop.wasmImportReceive(handle, unchecked((long)(maxResults)), ptr);

            Result<global::System.Collections.Generic.List<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.IncomingDatagram>, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted9;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    var array6 = new global::System.Collections.Generic.List<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.IncomingDatagram>(new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]);
                    for (int index = 0; index < new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]; ++index) {
                        nint basePtr1 = new global::System.Span<nint>((void*)((byte*)ptr + 4), 1)[0] + (index * 40);

                        var array = new byte[new global::System.Span<int>((void*)((byte*)basePtr1 + 4), 1)[0]];
                        new global::System.Span<byte>((void*)(new global::System.Span<nint>((void*)((byte*)basePtr1 + 0), 1)[0]), new global::System.Span<int>((void*)((byte*)basePtr1 + 4), 1)[0]).CopyTo(new global::System.Span<byte>(array));

                        if (new global::System.Span<int>((void*)((byte*)basePtr1 + 4), 1)[0] > 0) {
                            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr1 + 0), 1)[0]);
                        }

                        global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress lifted;

                        switch (new global::System.Span<byte>((byte*)basePtr1 + 8, 1)[0]) {
                            case 0: {

                                lifted = global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress.Ipv4(new global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv4SocketAddress (
                                ((ushort)new global::System.Span<ushort>((void*)((byte*)basePtr1 + 12), 1)[0]), (((byte)new global::System.Span<byte>((byte*)basePtr1 + 14, 1)[0]), ((byte)new global::System.Span<byte>((byte*)basePtr1 + 15, 1)[0]), ((byte)new global::System.Span<byte>((byte*)basePtr1 + 16, 1)[0]), ((byte)new global::System.Span<byte>((byte*)basePtr1 + 17, 1)[0]))));
                                break;
                            }
                            case 1: {

                                lifted = global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress.Ipv6(new global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv6SocketAddress (
                                ((ushort)new global::System.Span<ushort>((void*)((byte*)basePtr1 + 12), 1)[0]), unchecked((uint)(new global::System.Span<int>((void*)((byte*)basePtr1 + 16), 1)[0])), (((ushort)new global::System.Span<ushort>((void*)((byte*)basePtr1 + 20), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)basePtr1 + 22), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)basePtr1 + 24), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)basePtr1 + 26), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)basePtr1 + 28), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)basePtr1 + 30), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)basePtr1 + 32), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)basePtr1 + 34), 1)[0])), unchecked((uint)(new global::System.Span<int>((void*)((byte*)basePtr1 + 36), 1)[0]))));
                                break;
                            }

                            default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)basePtr1 + 8, 1)[0]);
                        }

                        array6.Add(new global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.IncomingDatagram (
                        array, lifted));
                    }

                    if (new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0] > 0) {
                        global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)ptr + 4), 1)[0]);
                    }

                    lifted9 = Result<global::System.Collections.Generic.List<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.IncomingDatagram>, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(array6);
                    break;
                }
                case 1: {

                    lifted9 = Result<global::System.Collections.Generic.List<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.IncomingDatagram>, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted9.IsOk)
            {
                var tmp = lifted9.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted9.AsErr!, 0);
            }

        }

        public  unsafe global::ParserPluginWorld.wit.Imports.wasi.io.v0_2_0.IPollImports.Pollable Subscribe()
        {
            var handle = this.Handle;
            var result =  UdpImportsInterop.IncomingDatagramStream.SubscribeWasmInterop.wasmImportSubscribe(handle);
            var resource = new global::ParserPluginWorld.wit.Imports.wasi.io.v0_2_0.IPollImports.Pollable(new global::ParserPluginWorld.wit.Imports.wasi.io.v0_2_0.IPollImports.Pollable.THandle(result));
            return resource;

        }

    }

    public class OutgoingDatagramStream: global::System.IDisposable {
        internal int Handle { get; set; }

        public readonly record struct THandle(int Handle);

        public OutgoingDatagramStream(THandle handle) {
            Handle = handle.Handle;
        }

        public void Dispose() {
            Dispose(true);
        }

        [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[resource-drop]outgoing-datagram-stream"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
        private static extern void wasmImportResourceDrop(int p0);

        protected virtual void Dispose(bool disposing) {
            if (disposing && Handle != 0) {
                wasmImportResourceDrop(Handle);
                Handle = 0;
            }
        }

        public  unsafe ulong CheckSend()
        {
            var handle = this.Handle;

            var retArea = stackalloc ulong[3];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 8);
            UdpImportsInterop.OutgoingDatagramStream.CheckSendWasmInterop.wasmImportCheckSend(handle, ptr);

            Result<ulong, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<ulong, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(unchecked((ulong)(new global::System.Span<long>((void*)((byte*)ptr + 8), 1)[0])));
                    break;
                }
                case 1: {

                    lifted = Result<ulong, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 8, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe ulong Send(global::System.Collections.Generic.List<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.OutgoingDatagram> datagrams)
        {
            var cleanups = new global::System.Collections.Generic.List<global::System.Action>();
            var handle = this.Handle;

            void* address;
            if ((44 * datagrams.Count) < 1024) {
                var retArea = stackalloc uint[11 * datagrams.Count + 1];
                address = MemoryHelper.AlignStackPtr(retArea, 4);
            }
            else
            {
                var bufferSize = 44 * (nuint)datagrams.Count;
                address = global::System.Runtime.InteropServices.NativeMemory.AlignedAlloc(bufferSize, 4);
                cleanups.Add(() => global::System.Runtime.InteropServices.NativeMemory.AlignedFree(address));
            }

            for (int index = 0; index < datagrams.Count; ++index) {
                global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.OutgoingDatagram element = datagrams[index];
                int basePtr = (int)address + (index * 44);

                var gcHandle = global::System.Runtime.InteropServices.GCHandle.Alloc(element.data, global::System.Runtime.InteropServices.GCHandleType.Pinned);
                var listPtr = gcHandle.AddrOfPinnedObject();
                cleanups.Add(()=> gcHandle.Free());
                new global::System.Span<int>((void*)((byte*)basePtr + 4), 1)[0] = (element.data).Length;
                new global::System.Span<nint>((void*)((byte*)basePtr + 0), 1)[0] = (nint)(nint)listPtr;

                if (element.remoteAddress != null) {
                    var payload4 = (global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress) element.remoteAddress;
                    *(byte*)(basePtr + 8) = (byte)1;

                    switch (payload4.Tag) {
                        case 0: {
                            global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv4SocketAddress payload7 = payload4.AsIpv4;
                            *(byte*)(basePtr + 12) = (byte)0;
                            new global::System.Span<short>((void*)((byte*)basePtr + 16), 1)[0] = (short)payload7.port;
                            *(byte*)(basePtr + 18) = (byte)payload7.address.Item1;
                            *(byte*)(basePtr + 19) = (byte)payload7.address.Item2;
                            *(byte*)(basePtr + 20) = (byte)payload7.address.Item3;
                            *(byte*)(basePtr + 21) = (byte)payload7.address.Item4;

                            break;
                        }
                        case 1: {
                            global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv6SocketAddress payload10 = payload4.AsIpv6;
                            *(byte*)(basePtr + 12) = (byte)1;
                            new global::System.Span<short>((void*)((byte*)basePtr + 16), 1)[0] = (short)payload10.port;
                            new global::System.Span<int>((void*)((byte*)basePtr + 20), 1)[0] = unchecked((int)(payload10.flowInfo));
                            new global::System.Span<short>((void*)((byte*)basePtr + 24), 1)[0] = (short)payload10.address.Item1;
                            new global::System.Span<short>((void*)((byte*)basePtr + 26), 1)[0] = (short)payload10.address.Item2;
                            new global::System.Span<short>((void*)((byte*)basePtr + 28), 1)[0] = (short)payload10.address.Item3;
                            new global::System.Span<short>((void*)((byte*)basePtr + 30), 1)[0] = (short)payload10.address.Item4;
                            new global::System.Span<short>((void*)((byte*)basePtr + 32), 1)[0] = (short)payload10.address.Item5;
                            new global::System.Span<short>((void*)((byte*)basePtr + 34), 1)[0] = (short)payload10.address.Item6;
                            new global::System.Span<short>((void*)((byte*)basePtr + 36), 1)[0] = (short)payload10.address.Item7;
                            new global::System.Span<short>((void*)((byte*)basePtr + 38), 1)[0] = (short)payload10.address.Item8;
                            new global::System.Span<int>((void*)((byte*)basePtr + 40), 1)[0] = unchecked((int)(payload10.scopeId));

                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant: " + payload4);
                    }

                } else {

                    *(byte*)(basePtr + 8) = (byte)0;

                }

            }

            var retArea11 = stackalloc ulong[3];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea11, 8);
            UdpImportsInterop.OutgoingDatagramStream.SendWasmInterop.wasmImportSend(handle, (int)address, datagrams.Count, ptr);

            Result<ulong, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<ulong, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(unchecked((ulong)(new global::System.Span<long>((void*)((byte*)ptr + 8), 1)[0])));
                    break;
                }
                case 1: {

                    lifted = Result<ulong, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 8, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe global::ParserPluginWorld.wit.Imports.wasi.io.v0_2_0.IPollImports.Pollable Subscribe()
        {
            var handle = this.Handle;
            var result =  UdpImportsInterop.OutgoingDatagramStream.SubscribeWasmInterop.wasmImportSubscribe(handle);
            var resource = new global::ParserPluginWorld.wit.Imports.wasi.io.v0_2_0.IPollImports.Pollable(new global::ParserPluginWorld.wit.Imports.wasi.io.v0_2_0.IPollImports.Pollable.THandle(result));
            return resource;

        }

    }

}
