// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ParserPluginWorld.wit.Imports.wasi.cli.v0_2_0;

public interface IStdoutImports {

    public static unsafe global::ParserPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream GetStdout()
    {
        var result =  StdoutImportsInterop.GetStdoutWasmInterop.wasmImportGetStdout();
        var resource = new global::ParserPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream(new global::ParserPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream.THandle(result));
        return resource;

    }

}
