// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;

namespace ParserPluginWorld.wit.Imports.local.logProcess.v0_3_0
{
    public static class PipelineProcessImportsInterop {

    }
}
