// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;

namespace ParserPluginWorld.wit.Imports.wasi.cli.v0_2_0
{
    public static class StdoutImportsInterop {

        public static class GetStdoutWasmInterop
        {
            [global::System.Runtime.InteropServices.DllImportAttribute("wasi:cli/stdout@0.2.0", EntryPoint = "get-stdout"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
            public static extern int wasmImportGetStdout();
        }

    }
}
