// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;

namespace ParserPluginWorld.wit.Imports.wasi.cli.v0_2_0
{
    public static class TerminalStderrImportsInterop {

        public static class GetTerminalStderrWasmInterop
        {
            [global::System.Runtime.InteropServices.DllImportAttribute("wasi:cli/terminal-stderr@0.2.0", EntryPoint = "get-terminal-stderr"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
            public static extern void wasmImportGetTerminalStderr(nint p0);
        }

    }
}
