// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.InteropServices;
using System.Collections.Concurrent;
using System.Threading;
using System.Threading.Tasks;

namespace ParserPluginWorld {

    public interface IParserPluginWorldImports{

    }

    public interface IParserPluginWorldExports{
        static abstract global::System.Collections.Generic.List<global::ParserPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.ParsedEntry> Parse(global::System.Collections.Generic.List<string> rawData);

        static abstract ulong ReportUsage();

    }

    public readonly struct None {}

    [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential)]
    public readonly struct Result<TOk, TErr>
    {
        public readonly byte Tag;
        private readonly object value;

        private Result(byte tag, object value)
        {
            Tag = tag;
            this.value = value;
        }

        public static Result<TOk, TErr> Ok(TOk ok)
        {
            return new Result<TOk, TErr>(Tags.Ok, ok!);
        }

        public static Result<TOk, TErr> Err(TErr err)
        {
            return new Result<TOk, TErr>(Tags.Err, err!);
        }

        public bool IsOk => Tag == Tags.Ok;
        public bool IsErr => Tag == Tags.Err;

        public TOk AsOk
        {
            get
            {
                if (Tag == Tags.Ok)
                {
                    return (TOk)value;
                }

                throw new global::System.ArgumentException("expected k, got " + Tag);
            }
        }

        public TErr AsErr
        {
            get
            {
                if (Tag == Tags.Err)
                {
                    return (TErr)value;
                }

                throw new global::System.ArgumentException("expected Err, got " + Tag);
            }
        }

        public class Tags
        {
            public const byte Ok = 0;
            public const byte Err = 1;
        }
    }

    public class Option<T> {
        private static Option<T> none = new ();

        private Option()
        {
            HasValue = false;
        }

        public Option(T v)
        {
            HasValue = true;
            Value = v;
        }

        public static Option<T> None => none;

        [global::System.Diagnostics.CodeAnalysis.MemberNotNullWhenAttribute(true, nameof(Value))]
        public bool HasValue { get; }

        public T? Value { get; }
    }

    public class WitException: global::System.Exception {
        public object Value { get; }
        public uint NestingLevel { get; }

        public WitException(object v, uint level)
        {
            Value = v;
            NestingLevel = level;
        }
    }

    public class WitException<T>: WitException {
        public T TypedValue { get { return (T)this.Value;} }

        public WitException(T v, uint level) : base(v!, level)
        {
        }
    }

    public static class InteropReturnArea
    {
        [global::System.Runtime.CompilerServices.InlineArrayAttribute(4)]
        [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential, Pack = 4)]
        internal struct ReturnArea
        {
            private uint buffer;

            internal unsafe nint AddressOfReturnArea()
            {
                return (nint)global::System.Runtime.CompilerServices.Unsafe.AsPointer(ref buffer);
            }
        }

        [global::System.ThreadStaticAttribute]
        [global::System.Runtime.CompilerServices.FixedAddressValueTypeAttribute]
        internal static ReturnArea returnArea = default;
    }

    public static class MemoryHelper
    {
        public static unsafe void* AlignStackPtr(void* stackAddress, uint alignment)
        {
            return (void*)(((nint)stackAddress) + ((int)alignment - 1) & -(int)alignment);
        }
    }

    namespace Imports {
        public partial class ParserPluginWorldImportsInterop : IParserPluginWorldImports
        {}
    }
    namespace Exports {
        public static class ParserPluginWorldInterop
        {

            [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "parse")]
            public static unsafe nint wasmExportParse(nint p0, int p1) {

                var array = new global::System.Collections.Generic.List<string>(p1);
                for (int index = 0; index < p1; ++index) {
                    nint basePtr = p0 + (index * 8);

                    var str = global::System.Text.Encoding.UTF8.GetString((byte*)new global::System.Span<nint>((void*)((byte*)basePtr + 0), 1)[0], new global::System.Span<int>((void*)((byte*)basePtr + 4), 1)[0]);
                    if (new global::System.Span<int>((void*)((byte*)basePtr + 4), 1)[0] > 0) {
                        global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr + 0), 1)[0]);
                    }

                    array.Add(str);
                }

                if (p1 > 0) {
                    global::System.Runtime.InteropServices.NativeMemory.Free((void*)p0);
                }
                Result<global::System.Collections.Generic.List<global::ParserPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.ParsedEntry>, global::ParserPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.ParseError> ret;

                try
                {

                    ret = Result<global::System.Collections.Generic.List<global::ParserPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.ParsedEntry>, global::ParserPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.ParseError>.Ok(ParserPluginWorldExportsImpl.Parse((array)));
                }
                catch (WitException e)
                {
                    switch (e.NestingLevel)
                    {
                        case 0:
                        {
                            ret = Result<global::System.Collections.Generic.List<global::ParserPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.ParsedEntry>, global::ParserPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.ParseError>.Err((global::ParserPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.ParseError) e.Value);
                            break;
                        }

                        default: throw new global::System.ArgumentException($"invalid nesting level: {e.NestingLevel}");
                    }
                }

                var ptr = InteropReturnArea.returnArea.AddressOfReturnArea();

                switch (ret.Tag) {
                    case 0: {
                        global::System.Collections.Generic.List<global::ParserPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.ParsedEntry> payload = ret.AsOk;
                        *(byte*)(ptr + 0) = (byte)0;

                        var bufferSize35 = 36 * (nuint)payload.Count;
                        void* address34 = global::System.Runtime.InteropServices.NativeMemory.AlignedAlloc(bufferSize35, 4);

                        for (int index33 = 0; index33 < payload.Count; ++index33) {
                            global::ParserPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.ParsedEntry element4 = payload[index33];
                            int basePtr5 = (int)address34 + (index33 * 36);

                            var stringSpan = global::System.MemoryExtensions.AsSpan(element4.timestamp);
                            var length = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan);
                            var strPtr = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length);
                            global::System.Text.Encoding.UTF8.GetBytes(stringSpan, new global::System.Span<byte>(strPtr, length));

                            new global::System.Span<int>((void*)((byte*)basePtr5 + 4), 1)[0] = length;
                            new global::System.Span<nint>((void*)((byte*)basePtr5 + 0), 1)[0] = (nint)(int)strPtr;
                            *(byte*)(basePtr5 + 8) = (byte)(int)element4.level;

                            var stringSpan12 = global::System.MemoryExtensions.AsSpan(element4.message);
                            var length10 = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan12);
                            var strPtr8 = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length10);
                            global::System.Text.Encoding.UTF8.GetBytes(stringSpan12, new global::System.Span<byte>(strPtr8, length10));

                            new global::System.Span<int>((void*)((byte*)basePtr5 + 16), 1)[0] = length10;
                            new global::System.Span<nint>((void*)((byte*)basePtr5 + 12), 1)[0] = (nint)(int)strPtr8;

                            var bufferSize = 16 * (nuint)element4.tags.Count;
                            void* address = global::System.Runtime.InteropServices.NativeMemory.AlignedAlloc(bufferSize, 4);

                            for (int index27 = 0; index27 < element4.tags.Count; ++index27) {
                                (string, string) element13 = element4.tags[index27];
                                int basePtr14 = (int)address + (index27 * 16);

                                var stringSpan21 = global::System.MemoryExtensions.AsSpan(element13.Item1);
                                var length19 = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan21);
                                var strPtr17 = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length19);
                                global::System.Text.Encoding.UTF8.GetBytes(stringSpan21, new global::System.Span<byte>(strPtr17, length19));

                                new global::System.Span<int>((void*)((byte*)basePtr14 + 4), 1)[0] = length19;
                                new global::System.Span<nint>((void*)((byte*)basePtr14 + 0), 1)[0] = (nint)(int)strPtr17;

                                var stringSpan26 = global::System.MemoryExtensions.AsSpan(element13.Item2);
                                var length24 = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan26);
                                var strPtr22 = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length24);
                                global::System.Text.Encoding.UTF8.GetBytes(stringSpan26, new global::System.Span<byte>(strPtr22, length24));

                                new global::System.Span<int>((void*)((byte*)basePtr14 + 12), 1)[0] = length24;
                                new global::System.Span<nint>((void*)((byte*)basePtr14 + 8), 1)[0] = (nint)(int)strPtr22;

                            }
                            new global::System.Span<int>((void*)((byte*)basePtr5 + 24), 1)[0] = element4.tags.Count;
                            new global::System.Span<nint>((void*)((byte*)basePtr5 + 20), 1)[0] = (nint)(int)address;

                            var stringSpan32 = global::System.MemoryExtensions.AsSpan(element4.targettag);
                            var length30 = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan32);
                            var strPtr28 = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length30);
                            global::System.Text.Encoding.UTF8.GetBytes(stringSpan32, new global::System.Span<byte>(strPtr28, length30));

                            new global::System.Span<int>((void*)((byte*)basePtr5 + 32), 1)[0] = length30;
                            new global::System.Span<nint>((void*)((byte*)basePtr5 + 28), 1)[0] = (nint)(int)strPtr28;

                        }
                        new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0] = payload.Count;
                        new global::System.Span<nint>((void*)((byte*)ptr + 4), 1)[0] = (nint)(int)address34;

                        break;
                    }
                    case 1: {
                        global::ParserPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.ParseError payload41 = ret.AsErr;
                        *(byte*)(ptr + 0) = (byte)1;

                        switch (payload41.Tag) {
                            case 0: {
                                string payload46 = payload41.AsInvalidFormat;
                                *(byte*)(ptr + 4) = (byte)0;

                                var stringSpan51 = global::System.MemoryExtensions.AsSpan(payload46);
                                var length49 = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan51);
                                var strPtr47 = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length49);
                                global::System.Text.Encoding.UTF8.GetBytes(stringSpan51, new global::System.Span<byte>(strPtr47, length49));

                                new global::System.Span<int>((void*)((byte*)ptr + 12), 1)[0] = length49;
                                new global::System.Span<nint>((void*)((byte*)ptr + 8), 1)[0] = (nint)(int)strPtr47;

                                break;
                            }
                            case 1: {
                                ushort payload56 = payload41.AsUnsupportedVersion;
                                *(byte*)(ptr + 4) = (byte)1;
                                new global::System.Span<short>((void*)((byte*)ptr + 8), 1)[0] = (short)payload56;

                                break;
                            }
                            case 2: {

                                *(byte*)(ptr + 4) = (byte)2;

                                break;
                            }

                            default: throw new global::System.ArgumentException("invalid discriminant: " + payload41);
                        }

                        break;
                    }

                    default: throw new global::System.ArgumentException("invalid discriminant: " + ret);
                }
                return ptr;

            }

            [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "cabi_post_parse")]
            public static unsafe void cabi_post_wasmExportParse(nint p0) {

                switch (new global::System.Span<byte>((byte*)p0 + 0, 1)[0]) {
                    case 0: {

                        for (int index8 = 0; index8 < new global::System.Span<int>((void*)((byte*)p0 + 8), 1)[0]; ++index8) {
                            int basePtr1 = (int)new global::System.Span<nint>((void*)((byte*)p0 + 4), 1)[0] + (index8 * 36);
                            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr1 + 0), 1)[0]);
                            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr1 + 12), 1)[0]);

                            for (int index = 0; index < new global::System.Span<int>((void*)((byte*)basePtr1 + 24), 1)[0]; ++index) {
                                int basePtr5 = (int)new global::System.Span<nint>((void*)((byte*)basePtr1 + 20), 1)[0] + (index * 16);
                                global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr5 + 0), 1)[0]);
                                global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr5 + 8), 1)[0]);

                            }
                            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr1 + 20), 1)[0]);
                            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr1 + 28), 1)[0]);

                        }
                        global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)p0 + 4), 1)[0]);

                        break;
                    }
                    case 1: {

                        switch (new global::System.Span<byte>((byte*)p0 + 4, 1)[0]) {
                            case 0: {
                                global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)p0 + 8), 1)[0]);

                                break;
                            }
                            case 1: {

                                break;
                            }
                            case 2: {

                                break;
                            }
                        }

                        break;
                    }
                }

            }

            [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "report-usage")]
            public static unsafe long wasmExportReportUsage() {

                ulong ret;
                ret = ParserPluginWorldExportsImpl.ReportUsage();
                return unchecked((long)(ret));

            }
        }
    }

}
