// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0;

public interface IUdpCreateSocketImports {

    public static unsafe global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.UdpSocket CreateUdpSocket(global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpAddressFamily addressFamily)
    {

        var retArea = stackalloc uint[3];
        var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
        UdpCreateSocketImportsInterop.CreateUdpSocketWasmInterop.wasmImportCreateUdpSocket((int)addressFamily, ptr);

        Result<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.UdpSocket, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

        switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
            case 0: {
                var resource = new global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.UdpSocket(new global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.UdpSocket.THandle(new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0]));

                lifted = Result<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.UdpSocket, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(resource);
                break;
            }
            case 1: {

                lifted = Result<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.IUdpImports.UdpSocket, global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                break;
            }

            default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
        }
        if (lifted.IsOk)
        {
            var tmp = lifted.AsOk;
            return tmp;
        }
        else
        {
            throw new WitException<global::ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
        }

    }

}
