// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.InteropServices;
using System.Collections.Concurrent;
using System.Threading;
using System.Threading.Tasks;

namespace ParserPluginWorld {

    public interface IParserPluginWorldImports{

    }

    public interface IParserPluginWorldExports{
        static abstract global::System.Collections.Generic.List<global::ParserPluginWorld.wit.Imports.local.logProcess.v0_1_0.IPipelineProcessImports.ParsedEntry> Parse(global::System.Collections.Generic.List<string> rawData);

        static abstract ulong ReportUsage();

        static abstract void Reset();

    }

    public readonly struct None {}

    [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential)]
    public readonly struct Result<TOk, TErr>
    {
        public readonly byte Tag;
        private readonly object value;

        private Result(byte tag, object value)
        {
            Tag = tag;
            this.value = value;
        }

        public static Result<TOk, TErr> Ok(TOk ok)
        {
            return new Result<TOk, TErr>(Tags.Ok, ok!);
        }

        public static Result<TOk, TErr> Err(TErr err)
        {
            return new Result<TOk, TErr>(Tags.Err, err!);
        }

        public bool IsOk => Tag == Tags.Ok;
        public bool IsErr => Tag == Tags.Err;

        public TOk AsOk
        {
            get
            {
                if (Tag == Tags.Ok)
                {
                    return (TOk)value;
                }

                throw new global::System.ArgumentException("expected k, got " + Tag);
            }
        }

        public TErr AsErr
        {
            get
            {
                if (Tag == Tags.Err)
                {
                    return (TErr)value;
                }

                throw new global::System.ArgumentException("expected Err, got " + Tag);
            }
        }

        public class Tags
        {
            public const byte Ok = 0;
            public const byte Err = 1;
        }
    }

    public class Option<T> {
        private static Option<T> none = new ();

        private Option()
        {
            HasValue = false;
        }

        public Option(T v)
        {
            HasValue = true;
            Value = v;
        }

        public static Option<T> None => none;

        [global::System.Diagnostics.CodeAnalysis.MemberNotNullWhenAttribute(true, nameof(Value))]
        public bool HasValue { get; }

        public T? Value { get; }
    }

    public class WitException: global::System.Exception {
        public object Value { get; }
        public uint NestingLevel { get; }

        public WitException(object v, uint level)
        {
            Value = v;
            NestingLevel = level;
        }
    }

    public class WitException<T>: WitException {
        public T TypedValue { get { return (T)this.Value;} }

        public WitException(T v, uint level) : base(v!, level)
        {
        }
    }

    public static class InteropReturnArea
    {
        [global::System.Runtime.CompilerServices.InlineArrayAttribute(4)]
        [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential, Pack = 4)]
        internal struct ReturnArea
        {
            private uint buffer;

            internal unsafe nint AddressOfReturnArea()
            {
                return (nint)global::System.Runtime.CompilerServices.Unsafe.AsPointer(ref buffer);
            }
        }

        [global::System.ThreadStaticAttribute]
        [global::System.Runtime.CompilerServices.FixedAddressValueTypeAttribute]
        internal static ReturnArea returnArea = default;
    }

    public static class MemoryHelper
    {
        public static unsafe void* AlignStackPtr(void* stackAddress, uint alignment)
        {
            return (void*)(((nint)stackAddress) + ((int)alignment - 1) & -(int)alignment);
        }
    }

    namespace Imports {
        public partial class ParserPluginWorldImportsInterop : IParserPluginWorldImports
        {}
    }
    namespace Exports {
        public static class ParserPluginWorldInterop
        {

            [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "parse")]
            public static unsafe nint wasmExportParse(nint p0, int p1) {

                var array = new global::System.Collections.Generic.List<string>(p1);
                for (int index = 0; index < p1; ++index) {
                    nint basePtr = p0 + (index * 8);

                    var str = global::System.Text.Encoding.UTF8.GetString((byte*)new global::System.Span<nint>((void*)((byte*)basePtr + 0), 1)[0], new global::System.Span<int>((void*)((byte*)basePtr + 4), 1)[0]);
                    if (new global::System.Span<int>((void*)((byte*)basePtr + 4), 1)[0] > 0) {
                        global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr + 0), 1)[0]);
                    }

                    array.Add(str);
                }

                if (p1 > 0) {
                    global::System.Runtime.InteropServices.NativeMemory.Free((void*)p0);
                }
                Result<global::System.Collections.Generic.List<global::ParserPluginWorld.wit.Imports.local.logProcess.v0_1_0.IPipelineProcessImports.ParsedEntry>, global::ParserPluginWorld.wit.Imports.local.logProcess.v0_1_0.IPipelineProcessImports.ParseError> ret;

                try
                {

                    ret = Result<global::System.Collections.Generic.List<global::ParserPluginWorld.wit.Imports.local.logProcess.v0_1_0.IPipelineProcessImports.ParsedEntry>, global::ParserPluginWorld.wit.Imports.local.logProcess.v0_1_0.IPipelineProcessImports.ParseError>.Ok(ParserPluginWorldExportsImpl.Parse((array)));
                }
                catch (WitException e)
                {
                    switch (e.NestingLevel)
                    {
                        case 0:
                        {
                            ret = Result<global::System.Collections.Generic.List<global::ParserPluginWorld.wit.Imports.local.logProcess.v0_1_0.IPipelineProcessImports.ParsedEntry>, global::ParserPluginWorld.wit.Imports.local.logProcess.v0_1_0.IPipelineProcessImports.ParseError>.Err((global::ParserPluginWorld.wit.Imports.local.logProcess.v0_1_0.IPipelineProcessImports.ParseError) e.Value);
                            break;
                        }

                        default: throw new global::System.ArgumentException($"invalid nesting level: {e.NestingLevel}");
                    }
                }

                var ptr = InteropReturnArea.returnArea.AddressOfReturnArea();

                switch (ret.Tag) {
                    case 0: {
                        global::System.Collections.Generic.List<global::ParserPluginWorld.wit.Imports.local.logProcess.v0_1_0.IPipelineProcessImports.ParsedEntry> payload = ret.AsOk;
                        *(byte*)(ptr + 0) = (byte)0;

                        var bufferSize24 = 36 * (nuint)payload.Count;
                        void* address23 = global::System.Runtime.InteropServices.NativeMemory.AlignedAlloc(bufferSize24, 4);

                        for (int index22 = 0; index22 < payload.Count; ++index22) {
                            global::ParserPluginWorld.wit.Imports.local.logProcess.v0_1_0.IPipelineProcessImports.ParsedEntry element2 = payload[index22];
                            int basePtr3 = (int)address23 + (index22 * 36);

                            var stringSpan = global::System.MemoryExtensions.AsSpan(element2.timestamp);
                            var length = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan);
                            var strPtr = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length);
                            global::System.Text.Encoding.UTF8.GetBytes(stringSpan, new global::System.Span<byte>(strPtr, length));

                            new global::System.Span<int>((void*)((byte*)basePtr3 + 4), 1)[0] = length;
                            new global::System.Span<nint>((void*)((byte*)basePtr3 + 0), 1)[0] = (nint)(int)strPtr;
                            *(byte*)(basePtr3 + 8) = (byte)(int)element2.level;

                            var stringSpan8 = global::System.MemoryExtensions.AsSpan(element2.message);
                            var length6 = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan8);
                            var strPtr4 = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length6);
                            global::System.Text.Encoding.UTF8.GetBytes(stringSpan8, new global::System.Span<byte>(strPtr4, length6));

                            new global::System.Span<int>((void*)((byte*)basePtr3 + 16), 1)[0] = length6;
                            new global::System.Span<nint>((void*)((byte*)basePtr3 + 12), 1)[0] = (nint)(int)strPtr4;

                            var bufferSize = 16 * (nuint)element2.tags.Count;
                            void* address = global::System.Runtime.InteropServices.NativeMemory.AlignedAlloc(bufferSize, 4);

                            for (int index21 = 0; index21 < element2.tags.Count; ++index21) {
                                (string, string) element9 = element2.tags[index21];
                                int basePtr10 = (int)address + (index21 * 16);

                                var stringSpan15 = global::System.MemoryExtensions.AsSpan(element9.Item1);
                                var length13 = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan15);
                                var strPtr11 = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length13);
                                global::System.Text.Encoding.UTF8.GetBytes(stringSpan15, new global::System.Span<byte>(strPtr11, length13));

                                new global::System.Span<int>((void*)((byte*)basePtr10 + 4), 1)[0] = length13;
                                new global::System.Span<nint>((void*)((byte*)basePtr10 + 0), 1)[0] = (nint)(int)strPtr11;

                                var stringSpan20 = global::System.MemoryExtensions.AsSpan(element9.Item2);
                                var length18 = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan20);
                                var strPtr16 = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length18);
                                global::System.Text.Encoding.UTF8.GetBytes(stringSpan20, new global::System.Span<byte>(strPtr16, length18));

                                new global::System.Span<int>((void*)((byte*)basePtr10 + 12), 1)[0] = length18;
                                new global::System.Span<nint>((void*)((byte*)basePtr10 + 8), 1)[0] = (nint)(int)strPtr16;

                            }
                            new global::System.Span<int>((void*)((byte*)basePtr3 + 24), 1)[0] = element2.tags.Count;
                            new global::System.Span<nint>((void*)((byte*)basePtr3 + 20), 1)[0] = (nint)(int)address;

                            var stringSpanTt = global::System.MemoryExtensions.AsSpan(element2.targettag);
                            var lengthTt = global::System.Text.Encoding.UTF8.GetByteCount(stringSpanTt);
                            var strPtrTt = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)lengthTt);
                            global::System.Text.Encoding.UTF8.GetBytes(stringSpanTt, new global::System.Span<byte>(strPtrTt, lengthTt));

                            new global::System.Span<int>((void*)((byte*)basePtr3 + 32), 1)[0] = lengthTt;
                            new global::System.Span<nint>((void*)((byte*)basePtr3 + 28), 1)[0] = (nint)(int)strPtrTt;

                        }
                        new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0] = payload.Count;
                        new global::System.Span<nint>((void*)((byte*)ptr + 4), 1)[0] = (nint)(int)address23;

                        break;
                    }
                    case 1: {
                        global::ParserPluginWorld.wit.Imports.local.logProcess.v0_1_0.IPipelineProcessImports.ParseError payload28 = ret.AsErr;
                        *(byte*)(ptr + 0) = (byte)1;

                        switch (payload28.Tag) {
                            case 0: {
                                string payload31 = payload28.AsInvalidFormat;
                                *(byte*)(ptr + 4) = (byte)0;

                                var stringSpan36 = global::System.MemoryExtensions.AsSpan(payload31);
                                var length34 = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan36);
                                var strPtr32 = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length34);
                                global::System.Text.Encoding.UTF8.GetBytes(stringSpan36, new global::System.Span<byte>(strPtr32, length34));

                                new global::System.Span<int>((void*)((byte*)ptr + 12), 1)[0] = length34;
                                new global::System.Span<nint>((void*)((byte*)ptr + 8), 1)[0] = (nint)(int)strPtr32;

                                break;
                            }
                            case 1: {
                                ushort payload39 = payload28.AsUnsupportedVersion;
                                *(byte*)(ptr + 4) = (byte)1;
                                new global::System.Span<short>((void*)((byte*)ptr + 8), 1)[0] = (short)payload39;

                                break;
                            }
                            case 2: {

                                *(byte*)(ptr + 4) = (byte)2;

                                break;
                            }

                            default: throw new global::System.ArgumentException("invalid discriminant: " + payload28);
                        }

                        break;
                    }

                    default: throw new global::System.ArgumentException("invalid discriminant: " + ret);
                }
                return ptr;

            }

            [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "cabi_post_parse")]
            public static unsafe void cabi_post_wasmExportParse(nint p0) {

                switch (new global::System.Span<byte>((byte*)p0 + 0, 1)[0]) {
                    case 0: {

                        for (int index4 = 0; index4 < new global::System.Span<int>((void*)((byte*)p0 + 8), 1)[0]; ++index4) {
                            int basePtr1 = (int)new global::System.Span<nint>((void*)((byte*)p0 + 4), 1)[0] + (index4 * 36);
                            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr1 + 0), 1)[0]);
                            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr1 + 12), 1)[0]);

                            for (int index = 0; index < new global::System.Span<int>((void*)((byte*)basePtr1 + 24), 1)[0]; ++index) {
                                int basePtr3 = (int)new global::System.Span<nint>((void*)((byte*)basePtr1 + 20), 1)[0] + (index * 16);
                                global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr3 + 0), 1)[0]);
                                global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr3 + 8), 1)[0]);

                            }
                            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr1 + 20), 1)[0]);
                            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr1 + 28), 1)[0]);

                        }
                        global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)p0 + 4), 1)[0]);

                        break;
                    }
                    case 1: {

                        switch (new global::System.Span<byte>((byte*)p0 + 4, 1)[0]) {
                            case 0: {
                                global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)p0 + 8), 1)[0]);

                                break;
                            }
                            case 1: {

                                break;
                            }
                            case 2: {

                                break;
                            }
                        }

                        break;
                    }
                }

            }

            [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "report-usage")]
            public static unsafe long wasmExportReportUsage() {

                ulong ret;
                ret = ParserPluginWorldExportsImpl.ReportUsage();
                return unchecked((long)(ret));

            }

            [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "reset")]
            public static unsafe void wasmExportReset() {

                ParserPluginWorldExportsImpl.Reset();

            }
        }
    }

}
