// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ParserPluginWorld.wit.Imports.wasi.clocks.v0_2_0;

public interface IWallClockImports {

    public struct Datetime {
        public ulong seconds;
        public uint nanoseconds;

        public Datetime(ulong seconds, uint nanoseconds) {
            this.seconds = seconds;
            this.nanoseconds = nanoseconds;
        }
    }

    public static unsafe global::ParserPluginWorld.wit.Imports.wasi.clocks.v0_2_0.IWallClockImports.Datetime Now()
    {

        var retArea = stackalloc ulong[3];
        var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 8);
        WallClockImportsInterop.NowWasmInterop.wasmImportNow(ptr);
        return new global::ParserPluginWorld.wit.Imports.wasi.clocks.v0_2_0.IWallClockImports.Datetime (
        unchecked((ulong)(new global::System.Span<long>((void*)((byte*)ptr + 0), 1)[0])), unchecked((uint)(new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0])));

    }

    public static unsafe global::ParserPluginWorld.wit.Imports.wasi.clocks.v0_2_0.IWallClockImports.Datetime Resolution()
    {

        var retArea = stackalloc ulong[3];
        var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 8);
        WallClockImportsInterop.ResolutionWasmInterop.wasmImportResolution(ptr);
        return new global::ParserPluginWorld.wit.Imports.wasi.clocks.v0_2_0.IWallClockImports.Datetime (
        unchecked((ulong)(new global::System.Span<long>((void*)((byte*)ptr + 0), 1)[0])), unchecked((uint)(new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0])));

    }

}
