// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ParserPluginWorld.wit.Imports.wasi.cli.v0_2_0;

public interface ITerminalOutputImports {

    /**
    * The output side of a terminal.
    */

    public class TerminalOutput: global::System.IDisposable {
        internal int Handle { get; set; }

        public readonly record struct THandle(int Handle);

        public TerminalOutput(THandle handle) {
            Handle = handle.Handle;
        }

        public void Dispose() {
            Dispose(true);
        }

        [global::System.Runtime.InteropServices.DllImportAttribute("wasi:cli/terminal-output@0.2.0", EntryPoint = "[resource-drop]terminal-output"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
        private static extern void wasmImportResourceDrop(int p0);

        protected virtual void Dispose(bool disposing) {
            if (disposing && Handle != 0) {
                wasmImportResourceDrop(Handle);
                Handle = 0;
            }
        }

    }

}
