// Code generated by wit-bindgen-go. DO NOT EDIT.

package formatplugin

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "local:log-process-format".

//go:wasmexport format
//export format
func wasmexport_Format(structData0 *LogEntry, structData1 uint32) (result *cm.Result[cm.List[cm.List[uint8]], cm.List[cm.List[uint8]], struct{}]) {
	structData := cm.LiftList[cm.List[LogEntry]]((*LogEntry)(structData0), (uint32)(structData1))
	result_ := Exports.Format(structData)
	result = &result_
	return
}
