// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package formatplugin represents the world "local:log-process-format/format-plugin".
package formatplugin

import (
	pipelineprocess "example.com/internal/local/log-process-format/pipeline-process"
)

// LogEntry represents the type alias "local:log-process-format/format-plugin#log-entry".
//
// See [pipelineprocess.LogEntry] for more information.
type LogEntry = pipelineprocess.LogEntry
