// Code generated by wit-bindgen-go. DO NOT EDIT.

package formatplugin

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "local:log-process-format/format-plugin".
var Exports struct {
	// Format represents the caller-defined, exported function "format".
	//
	// 優化：回傳 list<list<u8>>，讓每一條結構化日誌對應一個獨立的編碼後 byte 陣列
	//
	//	format: func(struct-data: list<log-entry>) -> result<list<list<u8>>>
	Format func(structData cm.List[LogEntry]) (result cm.Result[cm.List[cm.List[uint8]], cm.List[cm.List[uint8]], struct{}])
}
