// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;

namespace ReductionPluginWorld.wit.Imports.local.logProcess.v0_3_0
{
    public static class PipelineProcessImportsInterop {

    }
}
