// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;

namespace ReductionPluginWorld.wit.Imports.wasi.random.v0_2_0
{
    public static class InsecureSeedImportsInterop {

        public static class InsecureSeedWasmInterop
        {
            [global::System.Runtime.InteropServices.DllImportAttribute("wasi:random/insecure-seed@0.2.0", EntryPoint = "insecure-seed"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
            public static extern void wasmImportInsecureSeed(nint p0);
        }

    }
}
