// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;

namespace ReductionPluginWorld.wit.Imports.wasi.cli.v0_2_0
{
    public static class StdinImportsInterop {

        public static class GetStdinWasmInterop
        {
            [global::System.Runtime.InteropServices.DllImportAttribute("wasi:cli/stdin@0.2.0", EntryPoint = "get-stdin"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
            public static extern int wasmImportGetStdin();
        }

    }
}
