// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ReductionPluginWorld.wit.Imports.wasi.random.v0_2_0;

public interface IInsecureSeedImports {

    public static unsafe (ulong, ulong) InsecureSeed()
    {

        var retArea = stackalloc ulong[3];
        var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 8);
        InsecureSeedImportsInterop.InsecureSeedWasmInterop.wasmImportInsecureSeed(ptr);
        return (unchecked((ulong)(new global::System.Span<long>((void*)((byte*)ptr + 0), 1)[0])), unchecked((ulong)(new global::System.Span<long>((void*)((byte*)ptr + 8), 1)[0])));

    }

}
