// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ReductionPluginWorld.wit.Imports.wasi.random.v0_2_0;

public interface IRandomImports {

    public static unsafe byte[] GetRandomBytes(ulong len)
    {

        var retArea = stackalloc uint[3];
        var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
        RandomImportsInterop.GetRandomBytesWasmInterop.wasmImportGetRandomBytes(unchecked((long)(len)), ptr);

        var array = new byte[new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0]];
        new global::System.Span<byte>((void*)(new global::System.Span<nint>((void*)((byte*)ptr + 0), 1)[0]), new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0]).CopyTo(new global::System.Span<byte>(array));

        if (new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0] > 0) {
            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)ptr + 0), 1)[0]);
        }
        return array;

    }

    public static unsafe ulong GetRandomU64()
    {
        var result =  RandomImportsInterop.GetRandomU64WasmInterop.wasmImportGetRandomU64();
        return unchecked((ulong)(result));

    }

}
