// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ReductionPluginWorld.wit.Imports.local.logProcess.v0_3_0;

public interface IPipelineProcessImports {

    public enum LogLevel {
        DEBUG, INFO, WARN, ERROR, CRIT, ALERT, EMERG
    }

    public struct LogEntry {
        public ulong id;
        public string timestamp;
        public LogLevel level;
        public string message;
        public global::System.Collections.Generic.List<(string, string)> tags;

        public LogEntry(ulong id, string timestamp, LogLevel level, string message, global::System.Collections.Generic.List<(string, string)> tags) {
            this.id = id;
            this.timestamp = timestamp;
            this.level = level;
            this.message = message;
            this.tags = tags;
        }
    }

    public class PluginError {
        public readonly byte Tag;
        private readonly object? value;

        private PluginError(byte tag, object? value) {
            this.Tag = tag;
            this.value = value;
        }

        public static PluginError InvalidInput(string invalidInput) {
            return new PluginError(Tags.InvalidInput, invalidInput);
        }

        public static PluginError ProcessingFailed(string processingFailed) {
            return new PluginError(Tags.ProcessingFailed, processingFailed);
        }

        public static PluginError ConfigError(string configError) {
            return new PluginError(Tags.ConfigError, configError);
        }

        public static PluginError UnknownId(ulong unknownId) {
            return new PluginError(Tags.UnknownId, unknownId);
        }

        public static PluginError InternalError() {
            return new PluginError(Tags.InternalError, null);
        }

        public string AsInvalidInput
        {
            get
            {
                if (Tag == Tags.InvalidInput)
                return (string)value!;
                else
                throw new global::System.ArgumentException("expected InvalidInput, got " + Tag);
            }
        }

        public string AsProcessingFailed
        {
            get
            {
                if (Tag == Tags.ProcessingFailed)
                return (string)value!;
                else
                throw new global::System.ArgumentException("expected ProcessingFailed, got " + Tag);
            }
        }

        public string AsConfigError
        {
            get
            {
                if (Tag == Tags.ConfigError)
                return (string)value!;
                else
                throw new global::System.ArgumentException("expected ConfigError, got " + Tag);
            }
        }

        public ulong AsUnknownId
        {
            get
            {
                if (Tag == Tags.UnknownId)
                return (ulong)value!;
                else
                throw new global::System.ArgumentException("expected UnknownId, got " + Tag);
            }
        }

        public class Tags {
            public const byte InvalidInput = 0;
            public const byte ProcessingFailed = 1;
            public const byte ConfigError = 2;
            public const byte UnknownId = 3;
            public const byte InternalError = 4;
        }
    }

    public struct FilterResult {
        public ulong id;
        public bool keep;

        public FilterResult(ulong id, bool keep) {
            this.id = id;
            this.keep = keep;
        }
    }

}
