// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;

namespace ReductionPluginWorld.wit.Imports.wasi.clocks.v0_2_0
{
    public static class MonotonicClockImportsInterop {

        public static class NowWasmInterop
        {
            [global::System.Runtime.InteropServices.DllImportAttribute("wasi:clocks/monotonic-clock@0.2.0", EntryPoint = "now"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
            public static extern long wasmImportNow();
        }

        public static class ResolutionWasmInterop
        {
            [global::System.Runtime.InteropServices.DllImportAttribute("wasi:clocks/monotonic-clock@0.2.0", EntryPoint = "resolution"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
            public static extern long wasmImportResolution();
        }

        public static class SubscribeInstantWasmInterop
        {
            [global::System.Runtime.InteropServices.DllImportAttribute("wasi:clocks/monotonic-clock@0.2.0", EntryPoint = "subscribe-instant"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
            public static extern int wasmImportSubscribeInstant(long p0);
        }

        public static class SubscribeDurationWasmInterop
        {
            [global::System.Runtime.InteropServices.DllImportAttribute("wasi:clocks/monotonic-clock@0.2.0", EntryPoint = "subscribe-duration"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
            public static extern int wasmImportSubscribeDuration(long p0);
        }

    }
}
