// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ReductionPluginWorld.wit.Imports.wasi.cli.v0_2_0;

public interface IEnvironmentImports {

    public static unsafe global::System.Collections.Generic.List<(string, string)> GetEnvironment()
    {

        var retArea = stackalloc uint[3];
        var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
        EnvironmentImportsInterop.GetEnvironmentWasmInterop.wasmImportGetEnvironment(ptr);

        var array = new global::System.Collections.Generic.List<(string, string)>(new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0]);
        for (int index = 0; index < new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0]; ++index) {
            nint basePtr = new global::System.Span<nint>((void*)((byte*)ptr + 0), 1)[0] + (index * 16);

            var str = global::System.Text.Encoding.UTF8.GetString((byte*)new global::System.Span<nint>((void*)((byte*)basePtr + 0), 1)[0], new global::System.Span<int>((void*)((byte*)basePtr + 4), 1)[0]);
            if (new global::System.Span<int>((void*)((byte*)basePtr + 4), 1)[0] > 0) {
                global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr + 0), 1)[0]);
            }

            var str0 = global::System.Text.Encoding.UTF8.GetString((byte*)new global::System.Span<nint>((void*)((byte*)basePtr + 8), 1)[0], new global::System.Span<int>((void*)((byte*)basePtr + 12), 1)[0]);
            if (new global::System.Span<int>((void*)((byte*)basePtr + 12), 1)[0] > 0) {
                global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr + 8), 1)[0]);
            }

            array.Add((str, str0));
        }

        if (new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0] > 0) {
            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)ptr + 0), 1)[0]);
        }
        return array;

    }

    public static unsafe global::System.Collections.Generic.List<string> GetArguments()
    {

        var retArea = stackalloc uint[3];
        var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
        EnvironmentImportsInterop.GetArgumentsWasmInterop.wasmImportGetArguments(ptr);

        var array = new global::System.Collections.Generic.List<string>(new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0]);
        for (int index = 0; index < new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0]; ++index) {
            nint basePtr = new global::System.Span<nint>((void*)((byte*)ptr + 0), 1)[0] + (index * 8);

            var str = global::System.Text.Encoding.UTF8.GetString((byte*)new global::System.Span<nint>((void*)((byte*)basePtr + 0), 1)[0], new global::System.Span<int>((void*)((byte*)basePtr + 4), 1)[0]);
            if (new global::System.Span<int>((void*)((byte*)basePtr + 4), 1)[0] > 0) {
                global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr + 0), 1)[0]);
            }

            array.Add(str);
        }

        if (new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0] > 0) {
            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)ptr + 0), 1)[0]);
        }
        return array;

    }

    public static unsafe string? InitialCwd()
    {

        var retArea = stackalloc uint[4];
        var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
        EnvironmentImportsInterop.InitialCwdWasmInterop.wasmImportInitialCwd(ptr);

        string? lifted;

        switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
            case 0: {
                lifted = null;
                break;
            }

            case 1: {

                var str = global::System.Text.Encoding.UTF8.GetString((byte*)new global::System.Span<nint>((void*)((byte*)ptr + 4), 1)[0], new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]);
                if (new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0] > 0) {
                    global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)ptr + 4), 1)[0]);
                }

                lifted = str;
                break;
            }

            default: throw new global::System.ArgumentException("invalid discriminant: " + (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]));
        }
        return lifted;

    }

}
