// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;

namespace ReductionPluginWorld.wit.Imports.wasi.cli.v0_2_0
{
    public static class ExitImportsInterop {

        public static class ExitWasmInterop
        {
            [global::System.Runtime.InteropServices.DllImportAttribute("wasi:cli/exit@0.2.0", EntryPoint = "exit"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
            public static extern void wasmImportExit(int p0);
        }

    }
}
