// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0;

public interface ITcpImports {

    public enum ShutdownType {
        RECEIVE, SEND, BOTH
    }

    public class TcpSocket: global::System.IDisposable {
        internal int Handle { get; set; }

        public readonly record struct THandle(int Handle);

        public TcpSocket(THandle handle) {
            Handle = handle.Handle;
        }

        public void Dispose() {
            Dispose(true);
        }

        [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/tcp@0.2.0", EntryPoint = "[resource-drop]tcp-socket"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
        private static extern void wasmImportResourceDrop(int p0);

        protected virtual void Dispose(bool disposing) {
            if (disposing && Handle != 0) {
                wasmImportResourceDrop(Handle);
                Handle = 0;
            }
        }

        public  unsafe void StartBind(global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Network network, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress localAddress)
        {
            var handle = this.Handle;
            var handle0 = network.Handle;

            int lowered;
            int lowered4;
            int lowered5;
            int lowered6;
            int lowered7;
            int lowered8;
            int lowered9;
            int lowered10;
            int lowered11;
            int lowered12;
            int lowered13;
            int lowered14;

            switch (localAddress.Tag) {
                case 0: {
                    global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv4SocketAddress payload = localAddress.AsIpv4;

                    lowered = 0;
                    lowered4 = payload.port;
                    lowered5 = payload.address.Item1;
                    lowered6 = payload.address.Item2;
                    lowered7 = payload.address.Item3;
                    lowered8 = payload.address.Item4;
                    lowered9 = 0;
                    lowered10 = 0;
                    lowered11 = 0;
                    lowered12 = 0;
                    lowered13 = 0;
                    lowered14 = 0;

                    break;
                }
                case 1: {
                    global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv6SocketAddress payload3 = localAddress.AsIpv6;

                    lowered = 1;
                    lowered4 = payload3.port;
                    lowered5 = unchecked((int)(payload3.flowInfo));
                    lowered6 = payload3.address.Item1;
                    lowered7 = payload3.address.Item2;
                    lowered8 = payload3.address.Item3;
                    lowered9 = payload3.address.Item4;
                    lowered10 = payload3.address.Item5;
                    lowered11 = payload3.address.Item6;
                    lowered12 = payload3.address.Item7;
                    lowered13 = payload3.address.Item8;
                    lowered14 = unchecked((int)(payload3.scopeId));

                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant: " + localAddress);
            }

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            TcpImportsInterop.TcpSocket.StartBindWasmInterop.wasmImportStartBind(handle, handle0, lowered, lowered4, lowered5, lowered6, lowered7, lowered8, lowered9, lowered10, lowered11, lowered12, lowered13, lowered14, ptr);

            Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(new global::ReductionPluginWorld.None());
                    break;
                }
                case 1: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe void FinishBind()
        {
            var handle = this.Handle;

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            TcpImportsInterop.TcpSocket.FinishBindWasmInterop.wasmImportFinishBind(handle, ptr);

            Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(new global::ReductionPluginWorld.None());
                    break;
                }
                case 1: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe void StartConnect(global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Network network, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress remoteAddress)
        {
            var handle = this.Handle;
            var handle0 = network.Handle;

            int lowered;
            int lowered4;
            int lowered5;
            int lowered6;
            int lowered7;
            int lowered8;
            int lowered9;
            int lowered10;
            int lowered11;
            int lowered12;
            int lowered13;
            int lowered14;

            switch (remoteAddress.Tag) {
                case 0: {
                    global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv4SocketAddress payload = remoteAddress.AsIpv4;

                    lowered = 0;
                    lowered4 = payload.port;
                    lowered5 = payload.address.Item1;
                    lowered6 = payload.address.Item2;
                    lowered7 = payload.address.Item3;
                    lowered8 = payload.address.Item4;
                    lowered9 = 0;
                    lowered10 = 0;
                    lowered11 = 0;
                    lowered12 = 0;
                    lowered13 = 0;
                    lowered14 = 0;

                    break;
                }
                case 1: {
                    global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv6SocketAddress payload3 = remoteAddress.AsIpv6;

                    lowered = 1;
                    lowered4 = payload3.port;
                    lowered5 = unchecked((int)(payload3.flowInfo));
                    lowered6 = payload3.address.Item1;
                    lowered7 = payload3.address.Item2;
                    lowered8 = payload3.address.Item3;
                    lowered9 = payload3.address.Item4;
                    lowered10 = payload3.address.Item5;
                    lowered11 = payload3.address.Item6;
                    lowered12 = payload3.address.Item7;
                    lowered13 = payload3.address.Item8;
                    lowered14 = unchecked((int)(payload3.scopeId));

                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant: " + remoteAddress);
            }

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            TcpImportsInterop.TcpSocket.StartConnectWasmInterop.wasmImportStartConnect(handle, handle0, lowered, lowered4, lowered5, lowered6, lowered7, lowered8, lowered9, lowered10, lowered11, lowered12, lowered13, lowered14, ptr);

            Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(new global::ReductionPluginWorld.None());
                    break;
                }
                case 1: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe (global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.InputStream, global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream) FinishConnect()
        {
            var handle = this.Handle;

            var retArea = stackalloc uint[4];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
            TcpImportsInterop.TcpSocket.FinishConnectWasmInterop.wasmImportFinishConnect(handle, ptr);

            Result<(global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.InputStream, global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream), global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {
                    var resource = new global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.InputStream(new global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.InputStream.THandle(new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0]));
                    var resource0 = new global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream(new global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream.THandle(new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]));

                    lifted = Result<(global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.InputStream, global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream), global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok((resource, resource0));
                    break;
                }
                case 1: {

                    lifted = Result<(global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.InputStream, global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream), global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe void StartListen()
        {
            var handle = this.Handle;

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            TcpImportsInterop.TcpSocket.StartListenWasmInterop.wasmImportStartListen(handle, ptr);

            Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(new global::ReductionPluginWorld.None());
                    break;
                }
                case 1: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe void FinishListen()
        {
            var handle = this.Handle;

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            TcpImportsInterop.TcpSocket.FinishListenWasmInterop.wasmImportFinishListen(handle, ptr);

            Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(new global::ReductionPluginWorld.None());
                    break;
                }
                case 1: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe (global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.ITcpImports.TcpSocket, global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.InputStream, global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream) Accept()
        {
            var handle = this.Handle;

            var retArea = stackalloc uint[5];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
            TcpImportsInterop.TcpSocket.AcceptWasmInterop.wasmImportAccept(handle, ptr);

            Result<(global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.ITcpImports.TcpSocket, global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.InputStream, global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream), global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {
                    var resource = new global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.ITcpImports.TcpSocket(new global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.ITcpImports.TcpSocket.THandle(new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0]));
                    var resource0 = new global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.InputStream(new global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.InputStream.THandle(new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]));
                    var resource1 = new global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream(new global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream.THandle(new global::System.Span<int>((void*)((byte*)ptr + 12), 1)[0]));

                    lifted = Result<(global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.ITcpImports.TcpSocket, global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.InputStream, global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream), global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok((resource, resource0, resource1));
                    break;
                }
                case 1: {

                    lifted = Result<(global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.ITcpImports.TcpSocket, global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.InputStream, global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream), global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress LocalAddress()
        {
            var handle = this.Handle;

            var retArea = stackalloc uint[10];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
            TcpImportsInterop.TcpSocket.LocalAddressWasmInterop.wasmImportLocalAddress(handle, ptr);

            Result<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted6;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress lifted;

                    switch (new global::System.Span<byte>((byte*)ptr + 4, 1)[0]) {
                        case 0: {

                            lifted = global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress.Ipv4(new global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv4SocketAddress (
                            ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 8), 1)[0]), (((byte)new global::System.Span<byte>((byte*)ptr + 10, 1)[0]), ((byte)new global::System.Span<byte>((byte*)ptr + 11, 1)[0]), ((byte)new global::System.Span<byte>((byte*)ptr + 12, 1)[0]), ((byte)new global::System.Span<byte>((byte*)ptr + 13, 1)[0]))));
                            break;
                        }
                        case 1: {

                            lifted = global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress.Ipv6(new global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv6SocketAddress (
                            ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 8), 1)[0]), unchecked((uint)(new global::System.Span<int>((void*)((byte*)ptr + 12), 1)[0])), (((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 16), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 18), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 20), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 22), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 24), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 26), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 28), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 30), 1)[0])), unchecked((uint)(new global::System.Span<int>((void*)((byte*)ptr + 32), 1)[0]))));
                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    }

                    lifted6 = Result<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(lifted);
                    break;
                }
                case 1: {

                    lifted6 = Result<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted6.IsOk)
            {
                var tmp = lifted6.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted6.AsErr!, 0);
            }

        }

        public  unsafe global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress RemoteAddress()
        {
            var handle = this.Handle;

            var retArea = stackalloc uint[10];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
            TcpImportsInterop.TcpSocket.RemoteAddressWasmInterop.wasmImportRemoteAddress(handle, ptr);

            Result<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted6;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress lifted;

                    switch (new global::System.Span<byte>((byte*)ptr + 4, 1)[0]) {
                        case 0: {

                            lifted = global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress.Ipv4(new global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv4SocketAddress (
                            ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 8), 1)[0]), (((byte)new global::System.Span<byte>((byte*)ptr + 10, 1)[0]), ((byte)new global::System.Span<byte>((byte*)ptr + 11, 1)[0]), ((byte)new global::System.Span<byte>((byte*)ptr + 12, 1)[0]), ((byte)new global::System.Span<byte>((byte*)ptr + 13, 1)[0]))));
                            break;
                        }
                        case 1: {

                            lifted = global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress.Ipv6(new global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.Ipv6SocketAddress (
                            ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 8), 1)[0]), unchecked((uint)(new global::System.Span<int>((void*)((byte*)ptr + 12), 1)[0])), (((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 16), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 18), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 20), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 22), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 24), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 26), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 28), 1)[0]), ((ushort)new global::System.Span<ushort>((void*)((byte*)ptr + 30), 1)[0])), unchecked((uint)(new global::System.Span<int>((void*)((byte*)ptr + 32), 1)[0]))));
                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    }

                    lifted6 = Result<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(lifted);
                    break;
                }
                case 1: {

                    lifted6 = Result<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpSocketAddress, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted6.IsOk)
            {
                var tmp = lifted6.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted6.AsErr!, 0);
            }

        }

        public  unsafe bool IsListening()
        {
            var handle = this.Handle;
            var result =  TcpImportsInterop.TcpSocket.IsListeningWasmInterop.wasmImportIsListening(handle);
            return (result != 0);

        }

        public  unsafe global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpAddressFamily AddressFamily()
        {
            var handle = this.Handle;
            var result =  TcpImportsInterop.TcpSocket.AddressFamilyWasmInterop.wasmImportAddressFamily(handle);
            return (global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.IpAddressFamily)result;

        }

        public  unsafe void SetListenBacklogSize(ulong value)
        {
            var handle = this.Handle;

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            TcpImportsInterop.TcpSocket.SetListenBacklogSizeWasmInterop.wasmImportSetListenBacklogSize(handle, unchecked((long)(value)), ptr);

            Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(new global::ReductionPluginWorld.None());
                    break;
                }
                case 1: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe bool KeepAliveEnabled()
        {
            var handle = this.Handle;

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            TcpImportsInterop.TcpSocket.KeepAliveEnabledWasmInterop.wasmImportKeepAliveEnabled(handle, ptr);

            Result<bool, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<bool, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok((new global::System.Span<byte>((byte*)ptr + 1, 1)[0] != 0));
                    break;
                }
                case 1: {

                    lifted = Result<bool, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe void SetKeepAliveEnabled(bool value)
        {
            var handle = this.Handle;

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            TcpImportsInterop.TcpSocket.SetKeepAliveEnabledWasmInterop.wasmImportSetKeepAliveEnabled(handle, (value ? 1 : 0), ptr);

            Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(new global::ReductionPluginWorld.None());
                    break;
                }
                case 1: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe ulong KeepAliveIdleTime()
        {
            var handle = this.Handle;

            var retArea = stackalloc ulong[3];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 8);
            TcpImportsInterop.TcpSocket.KeepAliveIdleTimeWasmInterop.wasmImportKeepAliveIdleTime(handle, ptr);

            Result<ulong, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<ulong, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(unchecked((ulong)(new global::System.Span<long>((void*)((byte*)ptr + 8), 1)[0])));
                    break;
                }
                case 1: {

                    lifted = Result<ulong, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 8, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe void SetKeepAliveIdleTime(ulong value)
        {
            var handle = this.Handle;

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            TcpImportsInterop.TcpSocket.SetKeepAliveIdleTimeWasmInterop.wasmImportSetKeepAliveIdleTime(handle, unchecked((long)(value)), ptr);

            Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(new global::ReductionPluginWorld.None());
                    break;
                }
                case 1: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe ulong KeepAliveInterval()
        {
            var handle = this.Handle;

            var retArea = stackalloc ulong[3];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 8);
            TcpImportsInterop.TcpSocket.KeepAliveIntervalWasmInterop.wasmImportKeepAliveInterval(handle, ptr);

            Result<ulong, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<ulong, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(unchecked((ulong)(new global::System.Span<long>((void*)((byte*)ptr + 8), 1)[0])));
                    break;
                }
                case 1: {

                    lifted = Result<ulong, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 8, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe void SetKeepAliveInterval(ulong value)
        {
            var handle = this.Handle;

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            TcpImportsInterop.TcpSocket.SetKeepAliveIntervalWasmInterop.wasmImportSetKeepAliveInterval(handle, unchecked((long)(value)), ptr);

            Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(new global::ReductionPluginWorld.None());
                    break;
                }
                case 1: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe uint KeepAliveCount()
        {
            var handle = this.Handle;

            var retArea = stackalloc uint[3];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
            TcpImportsInterop.TcpSocket.KeepAliveCountWasmInterop.wasmImportKeepAliveCount(handle, ptr);

            Result<uint, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<uint, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(unchecked((uint)(new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0])));
                    break;
                }
                case 1: {

                    lifted = Result<uint, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe void SetKeepAliveCount(uint value)
        {
            var handle = this.Handle;

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            TcpImportsInterop.TcpSocket.SetKeepAliveCountWasmInterop.wasmImportSetKeepAliveCount(handle, unchecked((int)(value)), ptr);

            Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(new global::ReductionPluginWorld.None());
                    break;
                }
                case 1: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe byte HopLimit()
        {
            var handle = this.Handle;

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            TcpImportsInterop.TcpSocket.HopLimitWasmInterop.wasmImportHopLimit(handle, ptr);

            Result<byte, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<byte, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(((byte)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]));
                    break;
                }
                case 1: {

                    lifted = Result<byte, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe void SetHopLimit(byte value)
        {
            var handle = this.Handle;

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            TcpImportsInterop.TcpSocket.SetHopLimitWasmInterop.wasmImportSetHopLimit(handle, value, ptr);

            Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(new global::ReductionPluginWorld.None());
                    break;
                }
                case 1: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe ulong ReceiveBufferSize()
        {
            var handle = this.Handle;

            var retArea = stackalloc ulong[3];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 8);
            TcpImportsInterop.TcpSocket.ReceiveBufferSizeWasmInterop.wasmImportReceiveBufferSize(handle, ptr);

            Result<ulong, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<ulong, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(unchecked((ulong)(new global::System.Span<long>((void*)((byte*)ptr + 8), 1)[0])));
                    break;
                }
                case 1: {

                    lifted = Result<ulong, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 8, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe void SetReceiveBufferSize(ulong value)
        {
            var handle = this.Handle;

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            TcpImportsInterop.TcpSocket.SetReceiveBufferSizeWasmInterop.wasmImportSetReceiveBufferSize(handle, unchecked((long)(value)), ptr);

            Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(new global::ReductionPluginWorld.None());
                    break;
                }
                case 1: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe ulong SendBufferSize()
        {
            var handle = this.Handle;

            var retArea = stackalloc ulong[3];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 8);
            TcpImportsInterop.TcpSocket.SendBufferSizeWasmInterop.wasmImportSendBufferSize(handle, ptr);

            Result<ulong, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<ulong, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(unchecked((ulong)(new global::System.Span<long>((void*)((byte*)ptr + 8), 1)[0])));
                    break;
                }
                case 1: {

                    lifted = Result<ulong, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 8, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe void SetSendBufferSize(ulong value)
        {
            var handle = this.Handle;

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            TcpImportsInterop.TcpSocket.SetSendBufferSizeWasmInterop.wasmImportSetSendBufferSize(handle, unchecked((long)(value)), ptr);

            Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(new global::ReductionPluginWorld.None());
                    break;
                }
                case 1: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

        public  unsafe global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IPollImports.Pollable Subscribe()
        {
            var handle = this.Handle;
            var result =  TcpImportsInterop.TcpSocket.SubscribeWasmInterop.wasmImportSubscribe(handle);
            var resource = new global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IPollImports.Pollable(new global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IPollImports.Pollable.THandle(result));
            return resource;

        }

        public  unsafe void Shutdown(global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.ITcpImports.ShutdownType shutdownType)
        {
            var handle = this.Handle;

            var retArea = stackalloc byte[2];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 1);
            TcpImportsInterop.TcpSocket.ShutdownWasmInterop.wasmImportShutdown(handle, (int)shutdownType, ptr);

            Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode> lifted;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Ok(new global::ReductionPluginWorld.None());
                    break;
                }
                case 1: {

                    lifted = Result<None, global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>.Err((global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode)new global::System.Span<byte>((byte*)ptr + 1, 1)[0]);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0.INetworkImports.ErrorCode>(lifted.AsErr!, 0);
            }

        }

    }

}
