// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ReductionPluginWorld.wit.Imports.wasi.cli.v0_2_0;

public interface ITerminalStderrImports {

    public static unsafe global::ReductionPluginWorld.wit.Imports.wasi.cli.v0_2_0.ITerminalOutputImports.TerminalOutput? GetTerminalStderr()
    {

        var retArea = stackalloc uint[3];
        var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
        TerminalStderrImportsInterop.GetTerminalStderrWasmInterop.wasmImportGetTerminalStderr(ptr);

        global::ReductionPluginWorld.wit.Imports.wasi.cli.v0_2_0.ITerminalOutputImports.TerminalOutput? lifted;

        switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
            case 0: {
                lifted = null;
                break;
            }

            case 1: {
                var resource = new global::ReductionPluginWorld.wit.Imports.wasi.cli.v0_2_0.ITerminalOutputImports.TerminalOutput(new global::ReductionPluginWorld.wit.Imports.wasi.cli.v0_2_0.ITerminalOutputImports.TerminalOutput.THandle(new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0]));

                lifted = resource;
                break;
            }

            default: throw new global::System.ArgumentException("invalid discriminant: " + (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]));
        }
        return lifted;

    }

}
