// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;

namespace ReductionPluginWorld.wit.Imports.wasi.clocks.v0_2_0
{
    public static class WallClockImportsInterop {

        public static class NowWasmInterop
        {
            [global::System.Runtime.InteropServices.DllImportAttribute("wasi:clocks/wall-clock@0.2.0", EntryPoint = "now"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
            public static extern void wasmImportNow(nint p0);
        }

        public static class ResolutionWasmInterop
        {
            [global::System.Runtime.InteropServices.DllImportAttribute("wasi:clocks/wall-clock@0.2.0", EntryPoint = "resolution"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
            public static extern void wasmImportResolution(nint p0);
        }

    }
}
