// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ReductionPluginWorld.wit.Imports.wasi.clocks.v0_2_0;

public interface IMonotonicClockImports {

    public static unsafe ulong Now()
    {
        var result =  MonotonicClockImportsInterop.NowWasmInterop.wasmImportNow();
        return unchecked((ulong)(result));

    }

    public static unsafe ulong Resolution()
    {
        var result =  MonotonicClockImportsInterop.ResolutionWasmInterop.wasmImportResolution();
        return unchecked((ulong)(result));

    }

    public static unsafe global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IPollImports.Pollable SubscribeInstant(ulong when)
    {
        var result =  MonotonicClockImportsInterop.SubscribeInstantWasmInterop.wasmImportSubscribeInstant(unchecked((long)(when)));
        var resource = new global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IPollImports.Pollable(new global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IPollImports.Pollable.THandle(result));
        return resource;

    }

    public static unsafe global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IPollImports.Pollable SubscribeDuration(ulong when)
    {
        var result =  MonotonicClockImportsInterop.SubscribeDurationWasmInterop.wasmImportSubscribeDuration(unchecked((long)(when)));
        var resource = new global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IPollImports.Pollable(new global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IPollImports.Pollable.THandle(result));
        return resource;

    }

}
