// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;

namespace ReductionPluginWorld.wit.Imports.wasi.sockets.v0_2_0
{
    public static class NetworkImportsInterop {

        internal static class Network
        {

        }

    }
}
