// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.InteropServices;
using System.Collections.Concurrent;
using System.Threading;
using System.Threading.Tasks;

namespace ReductionPluginWorld {

    public interface IReductionPluginWorldImports{

    }

    public interface IReductionPluginWorldExports{
        static abstract global::System.Collections.Generic.List<global::ReductionPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.FilterResult> Filter(global::System.Collections.Generic.List<global::ReductionPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.LogEntry> structData);

        static abstract ulong ReportUsage();

    }

    public readonly struct None {}

    [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential)]
    public readonly struct Result<TOk, TErr>
    {
        public readonly byte Tag;
        private readonly object value;

        private Result(byte tag, object value)
        {
            Tag = tag;
            this.value = value;
        }

        public static Result<TOk, TErr> Ok(TOk ok)
        {
            return new Result<TOk, TErr>(Tags.Ok, ok!);
        }

        public static Result<TOk, TErr> Err(TErr err)
        {
            return new Result<TOk, TErr>(Tags.Err, err!);
        }

        public bool IsOk => Tag == Tags.Ok;
        public bool IsErr => Tag == Tags.Err;

        public TOk AsOk
        {
            get
            {
                if (Tag == Tags.Ok)
                {
                    return (TOk)value;
                }

                throw new global::System.ArgumentException("expected k, got " + Tag);
            }
        }

        public TErr AsErr
        {
            get
            {
                if (Tag == Tags.Err)
                {
                    return (TErr)value;
                }

                throw new global::System.ArgumentException("expected Err, got " + Tag);
            }
        }

        public class Tags
        {
            public const byte Ok = 0;
            public const byte Err = 1;
        }
    }

    public class Option<T> {
        private static Option<T> none = new ();

        private Option()
        {
            HasValue = false;
        }

        public Option(T v)
        {
            HasValue = true;
            Value = v;
        }

        public static Option<T> None => none;

        [global::System.Diagnostics.CodeAnalysis.MemberNotNullWhenAttribute(true, nameof(Value))]
        public bool HasValue { get; }

        public T? Value { get; }
    }

    public class WitException: global::System.Exception {
        public object Value { get; }
        public uint NestingLevel { get; }

        public WitException(object v, uint level)
        {
            Value = v;
            NestingLevel = level;
        }
    }

    public class WitException<T>: WitException {
        public T TypedValue { get { return (T)this.Value;} }

        public WitException(T v, uint level) : base(v!, level)
        {
        }
    }

    public static class InteropReturnArea
    {
        [global::System.Runtime.CompilerServices.InlineArrayAttribute(3)]
        [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential, Pack = 8)]
        internal struct ReturnArea
        {
            private ulong buffer;

            internal unsafe nint AddressOfReturnArea()
            {
                return (nint)global::System.Runtime.CompilerServices.Unsafe.AsPointer(ref buffer);
            }
        }

        [global::System.ThreadStaticAttribute]
        [global::System.Runtime.CompilerServices.FixedAddressValueTypeAttribute]
        internal static ReturnArea returnArea = default;
    }

    public static class MemoryHelper
    {
        public static unsafe void* AlignStackPtr(void* stackAddress, uint alignment)
        {
            return (void*)(((nint)stackAddress) + ((int)alignment - 1) & -(int)alignment);
        }
    }

    namespace Imports {
        public partial class ReductionPluginWorldImportsInterop : IReductionPluginWorldImports
        {}
    }
    namespace Exports {
        public static class ReductionPluginWorldInterop
        {

            [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "filter")]
            public static unsafe nint wasmExportFilter(nint p0, int p1) {

                var array7 = new global::System.Collections.Generic.List<global::ReductionPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.LogEntry>(p1);
                for (int index8 = 0; index8 < p1; ++index8) {
                    nint basePtr = p0 + (index8 * 40);

                    var str = global::System.Text.Encoding.UTF8.GetString((byte*)new global::System.Span<nint>((void*)((byte*)basePtr + 8), 1)[0], new global::System.Span<int>((void*)((byte*)basePtr + 12), 1)[0]);
                    if (new global::System.Span<int>((void*)((byte*)basePtr + 12), 1)[0] > 0) {
                        global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr + 8), 1)[0]);
                    }

                    var str0 = global::System.Text.Encoding.UTF8.GetString((byte*)new global::System.Span<nint>((void*)((byte*)basePtr + 20), 1)[0], new global::System.Span<int>((void*)((byte*)basePtr + 24), 1)[0]);
                    if (new global::System.Span<int>((void*)((byte*)basePtr + 24), 1)[0] > 0) {
                        global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr + 20), 1)[0]);
                    }

                    var array = new global::System.Collections.Generic.List<(string, string)>(new global::System.Span<int>((void*)((byte*)basePtr + 32), 1)[0]);
                    for (int index = 0; index < new global::System.Span<int>((void*)((byte*)basePtr + 32), 1)[0]; ++index) {
                        nint basePtr2 = new global::System.Span<nint>((void*)((byte*)basePtr + 28), 1)[0] + (index * 16);

                        var str5 = global::System.Text.Encoding.UTF8.GetString((byte*)new global::System.Span<nint>((void*)((byte*)basePtr2 + 0), 1)[0], new global::System.Span<int>((void*)((byte*)basePtr2 + 4), 1)[0]);
                        if (new global::System.Span<int>((void*)((byte*)basePtr2 + 4), 1)[0] > 0) {
                            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr2 + 0), 1)[0]);
                        }

                        var str6 = global::System.Text.Encoding.UTF8.GetString((byte*)new global::System.Span<nint>((void*)((byte*)basePtr2 + 8), 1)[0], new global::System.Span<int>((void*)((byte*)basePtr2 + 12), 1)[0]);
                        if (new global::System.Span<int>((void*)((byte*)basePtr2 + 12), 1)[0] > 0) {
                            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr2 + 8), 1)[0]);
                        }

                        array.Add((str5, str6));
                    }

                    if (new global::System.Span<int>((void*)((byte*)basePtr + 32), 1)[0] > 0) {
                        global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr + 28), 1)[0]);
                    }

                    array7.Add(new global::ReductionPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.LogEntry (
                    unchecked((ulong)(new global::System.Span<long>((void*)((byte*)basePtr + 0), 1)[0])), str, (global::ReductionPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.LogLevel)new global::System.Span<byte>((byte*)basePtr + 16, 1)[0], str0, array));
                }

                if (p1 > 0) {
                    global::System.Runtime.InteropServices.NativeMemory.Free((void*)p0);
                }
                Result<global::System.Collections.Generic.List<global::ReductionPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.FilterResult>, global::ReductionPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.PluginError> ret;

                try
                {

                    ret = Result<global::System.Collections.Generic.List<global::ReductionPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.FilterResult>, global::ReductionPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.PluginError>.Ok(ReductionPluginWorldExportsImpl.Filter((array7)));
                }
                catch (WitException e)
                {
                    switch (e.NestingLevel)
                    {
                        case 0:
                        {
                            ret = Result<global::System.Collections.Generic.List<global::ReductionPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.FilterResult>, global::ReductionPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.PluginError>.Err((global::ReductionPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.PluginError) e.Value);
                            break;
                        }

                        default: throw new global::System.ArgumentException($"invalid nesting level: {e.NestingLevel}");
                    }
                }

                var ptr = InteropReturnArea.returnArea.AddressOfReturnArea();

                switch (ret.Tag) {
                    case 0: {
                        global::System.Collections.Generic.List<global::ReductionPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.FilterResult> payload = ret.AsOk;
                        *(byte*)(ptr + 0) = (byte)0;

                        var bufferSize = 16 * (nuint)payload.Count;
                        void* address = global::System.Runtime.InteropServices.NativeMemory.AlignedAlloc(bufferSize, 8);

                        for (int index17 = 0; index17 < payload.Count; ++index17) {
                            global::ReductionPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.FilterResult element13 = payload[index17];
                            int basePtr14 = (int)address + (index17 * 16);
                            new global::System.Span<long>((void*)((byte*)basePtr14 + 0), 1)[0] = unchecked((long)unchecked((long)(element13.id)));
                            *(byte*)(basePtr14 + 8) = (byte)(element13.keep ? 1 : 0);

                        }
                        new global::System.Span<int>((void*)((byte*)ptr + 12), 1)[0] = payload.Count;
                        new global::System.Span<nint>((void*)((byte*)ptr + 8), 1)[0] = (nint)(int)address;

                        break;
                    }
                    case 1: {
                        global::ReductionPluginWorld.wit.Imports.local.logProcess.v0_3_0.IPipelineProcessImports.PluginError payload22 = ret.AsErr;
                        *(byte*)(ptr + 0) = (byte)1;

                        switch (payload22.Tag) {
                            case 0: {
                                string payload27 = payload22.AsInvalidInput;
                                *(byte*)(ptr + 8) = (byte)0;

                                var stringSpan = global::System.MemoryExtensions.AsSpan(payload27);
                                var length = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan);
                                var strPtr = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length);
                                global::System.Text.Encoding.UTF8.GetBytes(stringSpan, new global::System.Span<byte>(strPtr, length));

                                new global::System.Span<int>((void*)((byte*)ptr + 20), 1)[0] = length;
                                new global::System.Span<nint>((void*)((byte*)ptr + 16), 1)[0] = (nint)(int)strPtr;

                                break;
                            }
                            case 1: {
                                string payload32 = payload22.AsProcessingFailed;
                                *(byte*)(ptr + 8) = (byte)1;

                                var stringSpan37 = global::System.MemoryExtensions.AsSpan(payload32);
                                var length35 = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan37);
                                var strPtr33 = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length35);
                                global::System.Text.Encoding.UTF8.GetBytes(stringSpan37, new global::System.Span<byte>(strPtr33, length35));

                                new global::System.Span<int>((void*)((byte*)ptr + 20), 1)[0] = length35;
                                new global::System.Span<nint>((void*)((byte*)ptr + 16), 1)[0] = (nint)(int)strPtr33;

                                break;
                            }
                            case 2: {
                                string payload42 = payload22.AsConfigError;
                                *(byte*)(ptr + 8) = (byte)2;

                                var stringSpan47 = global::System.MemoryExtensions.AsSpan(payload42);
                                var length45 = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan47);
                                var strPtr43 = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length45);
                                global::System.Text.Encoding.UTF8.GetBytes(stringSpan47, new global::System.Span<byte>(strPtr43, length45));

                                new global::System.Span<int>((void*)((byte*)ptr + 20), 1)[0] = length45;
                                new global::System.Span<nint>((void*)((byte*)ptr + 16), 1)[0] = (nint)(int)strPtr43;

                                break;
                            }
                            case 3: {
                                ulong payload52 = payload22.AsUnknownId;
                                *(byte*)(ptr + 8) = (byte)3;
                                new global::System.Span<long>((void*)((byte*)ptr + 16), 1)[0] = unchecked((long)unchecked((long)(payload52)));

                                break;
                            }
                            case 4: {

                                *(byte*)(ptr + 8) = (byte)4;

                                break;
                            }

                            default: throw new global::System.ArgumentException("invalid discriminant: " + payload22);
                        }

                        break;
                    }

                    default: throw new global::System.ArgumentException("invalid discriminant: " + ret);
                }
                return ptr;

            }

            [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "cabi_post_filter")]
            public static unsafe void cabi_post_wasmExportFilter(nint p0) {

                switch (new global::System.Span<byte>((byte*)p0 + 0, 1)[0]) {
                    case 0: {
                        global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)p0 + 8), 1)[0]);

                        break;
                    }
                    case 1: {

                        switch (new global::System.Span<byte>((byte*)p0 + 8, 1)[0]) {
                            case 0: {
                                global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)p0 + 16), 1)[0]);

                                break;
                            }
                            case 1: {
                                global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)p0 + 16), 1)[0]);

                                break;
                            }
                            case 2: {
                                global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)p0 + 16), 1)[0]);

                                break;
                            }
                            case 3: {

                                break;
                            }
                            case 4: {

                                break;
                            }
                        }

                        break;
                    }
                }

            }

            [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "report-usage")]
            public static unsafe long wasmExportReportUsage() {

                ulong ret;
                ret = ReductionPluginWorldExportsImpl.ReportUsage();
                return unchecked((long)(ret));

            }
        }
    }

}
