// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ReductionPluginWorld.wit.Imports.wasi.cli.v0_2_0;

public interface IStdinImports {

    public static unsafe global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.InputStream GetStdin()
    {
        var result =  StdinImportsInterop.GetStdinWasmInterop.wasmImportGetStdin();
        var resource = new global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.InputStream(new global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.InputStream.THandle(result));
        return resource;

    }

}
