// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ReductionPluginWorld.wit.Imports.wasi.cli.v0_2_0;

public interface IStdoutImports {

    public static unsafe global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream GetStdout()
    {
        var result =  StdoutImportsInterop.GetStdoutWasmInterop.wasmImportGetStdout();
        var resource = new global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream(new global::ReductionPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream.THandle(result));
        return resource;

    }

}
