// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
#ifndef __BINDINGS_FORMAT_PLUGIN_H
#define __BINDINGS_FORMAT_PLUGIN_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct format_plugin_string_t {
  uint8_t*ptr;
  size_t len;
} format_plugin_string_t;

typedef struct {
  format_plugin_string_t f0;
  format_plugin_string_t f1;
} format_plugin_tuple2_string_string_t;

typedef struct {
  format_plugin_tuple2_string_string_t *ptr;
  size_t len;
} format_plugin_list_tuple2_string_string_t;

typedef struct {
  format_plugin_string_t *ptr;
  size_t len;
} format_plugin_list_string_t;

typedef struct {
  bool is_some;
  format_plugin_string_t val;
} format_plugin_option_string_t;

typedef struct {
  bool is_err;
} wasi_cli_exit_result_void_void_t;

typedef struct wasi_io_error_own_error_t {
  int32_t __handle;
} wasi_io_error_own_error_t;

typedef struct wasi_io_error_borrow_error_t {
  int32_t __handle;
} wasi_io_error_borrow_error_t;

typedef struct wasi_io_poll_own_pollable_t {
  int32_t __handle;
} wasi_io_poll_own_pollable_t;

typedef struct wasi_io_poll_borrow_pollable_t {
  int32_t __handle;
} wasi_io_poll_borrow_pollable_t;

typedef struct {
  wasi_io_poll_borrow_pollable_t *ptr;
  size_t len;
} wasi_io_poll_list_borrow_pollable_t;

typedef struct {
  uint32_t *ptr;
  size_t len;
} format_plugin_list_u32_t;

typedef wasi_io_error_own_error_t wasi_io_streams_own_error_t;

typedef struct wasi_io_streams_stream_error_t {
  uint8_t tag;
  union {
    wasi_io_streams_own_error_t     last_operation_failed;
  } val;
} wasi_io_streams_stream_error_t;

#define WASI_IO_STREAMS_STREAM_ERROR_LAST_OPERATION_FAILED 0
#define WASI_IO_STREAMS_STREAM_ERROR_CLOSED 1

typedef struct wasi_io_streams_own_input_stream_t {
  int32_t __handle;
} wasi_io_streams_own_input_stream_t;

typedef struct wasi_io_streams_borrow_input_stream_t {
  int32_t __handle;
} wasi_io_streams_borrow_input_stream_t;

typedef struct wasi_io_streams_own_output_stream_t {
  int32_t __handle;
} wasi_io_streams_own_output_stream_t;

typedef struct wasi_io_streams_borrow_output_stream_t {
  int32_t __handle;
} wasi_io_streams_borrow_output_stream_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} format_plugin_list_u8_t;

typedef struct {
  bool is_err;
  union {
    format_plugin_list_u8_t ok;
    wasi_io_streams_stream_error_t err;
  } val;
} wasi_io_streams_result_list_u8_stream_error_t;

typedef struct {
  bool is_err;
  union {
    uint64_t ok;
    wasi_io_streams_stream_error_t err;
  } val;
} wasi_io_streams_result_u64_stream_error_t;

typedef wasi_io_poll_own_pollable_t wasi_io_streams_own_pollable_t;

typedef struct {
  bool is_err;
  union {
    wasi_io_streams_stream_error_t err;
  } val;
} wasi_io_streams_result_void_stream_error_t;

typedef wasi_io_streams_own_input_stream_t wasi_cli_stdin_own_input_stream_t;

typedef wasi_io_streams_own_output_stream_t wasi_cli_stdout_own_output_stream_t;

typedef wasi_io_streams_own_output_stream_t wasi_cli_stderr_own_output_stream_t;

typedef struct wasi_cli_terminal_input_own_terminal_input_t {
  int32_t __handle;
} wasi_cli_terminal_input_own_terminal_input_t;

typedef struct wasi_cli_terminal_input_borrow_terminal_input_t {
  int32_t __handle;
} wasi_cli_terminal_input_borrow_terminal_input_t;

typedef struct wasi_cli_terminal_output_own_terminal_output_t {
  int32_t __handle;
} wasi_cli_terminal_output_own_terminal_output_t;

typedef struct wasi_cli_terminal_output_borrow_terminal_output_t {
  int32_t __handle;
} wasi_cli_terminal_output_borrow_terminal_output_t;

typedef wasi_cli_terminal_input_own_terminal_input_t wasi_cli_terminal_stdin_own_terminal_input_t;

typedef struct {
  bool is_some;
  wasi_cli_terminal_stdin_own_terminal_input_t val;
} wasi_cli_terminal_stdin_option_own_terminal_input_t;

typedef wasi_cli_terminal_output_own_terminal_output_t wasi_cli_terminal_stdout_own_terminal_output_t;

typedef struct {
  bool is_some;
  wasi_cli_terminal_stdout_own_terminal_output_t val;
} wasi_cli_terminal_stdout_option_own_terminal_output_t;

typedef wasi_cli_terminal_output_own_terminal_output_t wasi_cli_terminal_stderr_own_terminal_output_t;

typedef struct {
  bool is_some;
  wasi_cli_terminal_stderr_own_terminal_output_t val;
} wasi_cli_terminal_stderr_option_own_terminal_output_t;

typedef uint64_t wasi_clocks_monotonic_clock_instant_t;

typedef uint64_t wasi_clocks_monotonic_clock_duration_t;

typedef wasi_io_poll_own_pollable_t wasi_clocks_monotonic_clock_own_pollable_t;

typedef struct wasi_clocks_wall_clock_datetime_t {
  uint64_t   seconds;
  uint32_t   nanoseconds;
} wasi_clocks_wall_clock_datetime_t;

typedef wasi_clocks_wall_clock_datetime_t wasi_filesystem_types_datetime_t;

typedef uint64_t wasi_filesystem_types_filesize_t;

typedef uint8_t wasi_filesystem_types_descriptor_type_t;

#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_TYPE_UNKNOWN 0
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_TYPE_BLOCK_DEVICE 1
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_TYPE_CHARACTER_DEVICE 2
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_TYPE_DIRECTORY 3
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_TYPE_FIFO 4
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_TYPE_SYMBOLIC_LINK 5
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_TYPE_REGULAR_FILE 6
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_TYPE_SOCKET 7

typedef uint8_t wasi_filesystem_types_descriptor_flags_t;

#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_FLAGS_READ (1 << 0)
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_FLAGS_WRITE (1 << 1)
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_FLAGS_FILE_INTEGRITY_SYNC (1 << 2)
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_FLAGS_DATA_INTEGRITY_SYNC (1 << 3)
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_FLAGS_REQUESTED_WRITE_SYNC (1 << 4)
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_FLAGS_MUTATE_DIRECTORY (1 << 5)

typedef uint8_t wasi_filesystem_types_path_flags_t;

#define WASI_FILESYSTEM_TYPES_PATH_FLAGS_SYMLINK_FOLLOW (1 << 0)

typedef uint8_t wasi_filesystem_types_open_flags_t;

#define WASI_FILESYSTEM_TYPES_OPEN_FLAGS_CREATE (1 << 0)
#define WASI_FILESYSTEM_TYPES_OPEN_FLAGS_DIRECTORY (1 << 1)
#define WASI_FILESYSTEM_TYPES_OPEN_FLAGS_EXCLUSIVE (1 << 2)
#define WASI_FILESYSTEM_TYPES_OPEN_FLAGS_TRUNCATE (1 << 3)

typedef uint64_t wasi_filesystem_types_link_count_t;

typedef struct {
  bool is_some;
  wasi_filesystem_types_datetime_t val;
} wasi_filesystem_types_option_datetime_t;

typedef struct wasi_filesystem_types_descriptor_stat_t {
  wasi_filesystem_types_descriptor_type_t   type;
  wasi_filesystem_types_link_count_t   link_count;
  wasi_filesystem_types_filesize_t   size;
  wasi_filesystem_types_option_datetime_t   data_access_timestamp;
  wasi_filesystem_types_option_datetime_t   data_modification_timestamp;
  wasi_filesystem_types_option_datetime_t   status_change_timestamp;
} wasi_filesystem_types_descriptor_stat_t;

typedef struct wasi_filesystem_types_new_timestamp_t {
  uint8_t tag;
  union {
    wasi_filesystem_types_datetime_t     timestamp;
  } val;
} wasi_filesystem_types_new_timestamp_t;

#define WASI_FILESYSTEM_TYPES_NEW_TIMESTAMP_NO_CHANGE 0
#define WASI_FILESYSTEM_TYPES_NEW_TIMESTAMP_NOW 1
#define WASI_FILESYSTEM_TYPES_NEW_TIMESTAMP_TIMESTAMP 2

typedef struct wasi_filesystem_types_directory_entry_t {
  wasi_filesystem_types_descriptor_type_t   type;
  format_plugin_string_t   name;
} wasi_filesystem_types_directory_entry_t;

typedef uint8_t wasi_filesystem_types_error_code_t;

#define WASI_FILESYSTEM_TYPES_ERROR_CODE_ACCESS 0
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_WOULD_BLOCK 1
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_ALREADY 2
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_BAD_DESCRIPTOR 3
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_BUSY 4
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_DEADLOCK 5
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_QUOTA 6
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_EXIST 7
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_FILE_TOO_LARGE 8
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_ILLEGAL_BYTE_SEQUENCE 9
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_IN_PROGRESS 10
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_INTERRUPTED 11
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_INVALID 12
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_IO 13
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_IS_DIRECTORY 14
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_LOOP 15
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_TOO_MANY_LINKS 16
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_MESSAGE_SIZE 17
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NAME_TOO_LONG 18
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NO_DEVICE 19
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NO_ENTRY 20
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NO_LOCK 21
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_INSUFFICIENT_MEMORY 22
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_INSUFFICIENT_SPACE 23
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NOT_DIRECTORY 24
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NOT_EMPTY 25
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NOT_RECOVERABLE 26
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_UNSUPPORTED 27
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NO_TTY 28
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NO_SUCH_DEVICE 29
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_OVERFLOW 30
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NOT_PERMITTED 31
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_PIPE 32
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_READ_ONLY 33
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_INVALID_SEEK 34
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_TEXT_FILE_BUSY 35
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_CROSS_DEVICE 36

typedef uint8_t wasi_filesystem_types_advice_t;

#define WASI_FILESYSTEM_TYPES_ADVICE_NORMAL 0
#define WASI_FILESYSTEM_TYPES_ADVICE_SEQUENTIAL 1
#define WASI_FILESYSTEM_TYPES_ADVICE_RANDOM 2
#define WASI_FILESYSTEM_TYPES_ADVICE_WILL_NEED 3
#define WASI_FILESYSTEM_TYPES_ADVICE_DONT_NEED 4
#define WASI_FILESYSTEM_TYPES_ADVICE_NO_REUSE 5

typedef struct wasi_filesystem_types_metadata_hash_value_t {
  uint64_t   lower;
  uint64_t   upper;
} wasi_filesystem_types_metadata_hash_value_t;

typedef struct wasi_filesystem_types_own_descriptor_t {
  int32_t __handle;
} wasi_filesystem_types_own_descriptor_t;

typedef struct wasi_filesystem_types_borrow_descriptor_t {
  int32_t __handle;
} wasi_filesystem_types_borrow_descriptor_t;

typedef struct wasi_filesystem_types_own_directory_entry_stream_t {
  int32_t __handle;
} wasi_filesystem_types_own_directory_entry_stream_t;

typedef struct wasi_filesystem_types_borrow_directory_entry_stream_t {
  int32_t __handle;
} wasi_filesystem_types_borrow_directory_entry_stream_t;

typedef wasi_io_streams_own_input_stream_t wasi_filesystem_types_own_input_stream_t;

typedef struct {
  bool is_err;
  union {
    wasi_filesystem_types_own_input_stream_t ok;
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_own_input_stream_error_code_t;

typedef wasi_io_streams_own_output_stream_t wasi_filesystem_types_own_output_stream_t;

typedef struct {
  bool is_err;
  union {
    wasi_filesystem_types_own_output_stream_t ok;
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_own_output_stream_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_void_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_filesystem_types_descriptor_flags_t ok;
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_descriptor_flags_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_filesystem_types_descriptor_type_t ok;
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_descriptor_type_error_code_t;

typedef struct {
  format_plugin_list_u8_t f0;
  bool f1;
} format_plugin_tuple2_list_u8_bool_t;

typedef struct {
  bool is_err;
  union {
    format_plugin_tuple2_list_u8_bool_t ok;
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_tuple2_list_u8_bool_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_filesystem_types_filesize_t ok;
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_filesize_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_filesystem_types_own_directory_entry_stream_t ok;
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_own_directory_entry_stream_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_filesystem_types_descriptor_stat_t ok;
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_descriptor_stat_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_filesystem_types_own_descriptor_t ok;
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_own_descriptor_error_code_t;

typedef struct {
  bool is_err;
  union {
    format_plugin_string_t ok;
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_string_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_filesystem_types_metadata_hash_value_t ok;
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_metadata_hash_value_error_code_t;

typedef struct {
  bool is_some;
  wasi_filesystem_types_directory_entry_t val;
} wasi_filesystem_types_option_directory_entry_t;

typedef struct {
  bool is_err;
  union {
    wasi_filesystem_types_option_directory_entry_t ok;
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_option_directory_entry_error_code_t;

typedef wasi_io_error_borrow_error_t wasi_filesystem_types_borrow_error_t;

typedef struct {
  bool is_some;
  wasi_filesystem_types_error_code_t val;
} wasi_filesystem_types_option_error_code_t;

typedef wasi_filesystem_types_own_descriptor_t wasi_filesystem_preopens_own_descriptor_t;

typedef struct {
  wasi_filesystem_preopens_own_descriptor_t f0;
  format_plugin_string_t f1;
} wasi_filesystem_preopens_tuple2_own_descriptor_string_t;

typedef struct {
  wasi_filesystem_preopens_tuple2_own_descriptor_string_t *ptr;
  size_t len;
} wasi_filesystem_preopens_list_tuple2_own_descriptor_string_t;

typedef struct wasi_sockets_network_own_network_t {
  int32_t __handle;
} wasi_sockets_network_own_network_t;

typedef struct wasi_sockets_network_borrow_network_t {
  int32_t __handle;
} wasi_sockets_network_borrow_network_t;

typedef uint8_t wasi_sockets_network_error_code_t;

#define WASI_SOCKETS_NETWORK_ERROR_CODE_UNKNOWN 0
#define WASI_SOCKETS_NETWORK_ERROR_CODE_ACCESS_DENIED 1
#define WASI_SOCKETS_NETWORK_ERROR_CODE_NOT_SUPPORTED 2
#define WASI_SOCKETS_NETWORK_ERROR_CODE_INVALID_ARGUMENT 3
#define WASI_SOCKETS_NETWORK_ERROR_CODE_OUT_OF_MEMORY 4
#define WASI_SOCKETS_NETWORK_ERROR_CODE_TIMEOUT 5
#define WASI_SOCKETS_NETWORK_ERROR_CODE_CONCURRENCY_CONFLICT 6
#define WASI_SOCKETS_NETWORK_ERROR_CODE_NOT_IN_PROGRESS 7
#define WASI_SOCKETS_NETWORK_ERROR_CODE_WOULD_BLOCK 8
#define WASI_SOCKETS_NETWORK_ERROR_CODE_INVALID_STATE 9
#define WASI_SOCKETS_NETWORK_ERROR_CODE_NEW_SOCKET_LIMIT 10
#define WASI_SOCKETS_NETWORK_ERROR_CODE_ADDRESS_NOT_BINDABLE 11
#define WASI_SOCKETS_NETWORK_ERROR_CODE_ADDRESS_IN_USE 12
#define WASI_SOCKETS_NETWORK_ERROR_CODE_REMOTE_UNREACHABLE 13
#define WASI_SOCKETS_NETWORK_ERROR_CODE_CONNECTION_REFUSED 14
#define WASI_SOCKETS_NETWORK_ERROR_CODE_CONNECTION_RESET 15
#define WASI_SOCKETS_NETWORK_ERROR_CODE_CONNECTION_ABORTED 16
#define WASI_SOCKETS_NETWORK_ERROR_CODE_DATAGRAM_TOO_LARGE 17
#define WASI_SOCKETS_NETWORK_ERROR_CODE_NAME_UNRESOLVABLE 18
#define WASI_SOCKETS_NETWORK_ERROR_CODE_TEMPORARY_RESOLVER_FAILURE 19
#define WASI_SOCKETS_NETWORK_ERROR_CODE_PERMANENT_RESOLVER_FAILURE 20

typedef uint8_t wasi_sockets_network_ip_address_family_t;

#define WASI_SOCKETS_NETWORK_IP_ADDRESS_FAMILY_IPV4 0
#define WASI_SOCKETS_NETWORK_IP_ADDRESS_FAMILY_IPV6 1

typedef struct wasi_sockets_network_ipv4_address_t {
  uint8_t   f0;
  uint8_t   f1;
  uint8_t   f2;
  uint8_t   f3;
} wasi_sockets_network_ipv4_address_t;

typedef struct wasi_sockets_network_ipv6_address_t {
  uint16_t   f0;
  uint16_t   f1;
  uint16_t   f2;
  uint16_t   f3;
  uint16_t   f4;
  uint16_t   f5;
  uint16_t   f6;
  uint16_t   f7;
} wasi_sockets_network_ipv6_address_t;

typedef struct wasi_sockets_network_ip_address_t {
  uint8_t tag;
  union {
    wasi_sockets_network_ipv4_address_t     ipv4;
    wasi_sockets_network_ipv6_address_t     ipv6;
  } val;
} wasi_sockets_network_ip_address_t;

#define WASI_SOCKETS_NETWORK_IP_ADDRESS_IPV4 0
#define WASI_SOCKETS_NETWORK_IP_ADDRESS_IPV6 1

typedef struct wasi_sockets_network_ipv4_socket_address_t {
  uint16_t   port;
  wasi_sockets_network_ipv4_address_t   address;
} wasi_sockets_network_ipv4_socket_address_t;

typedef struct wasi_sockets_network_ipv6_socket_address_t {
  uint16_t   port;
  uint32_t   flow_info;
  wasi_sockets_network_ipv6_address_t   address;
  uint32_t   scope_id;
} wasi_sockets_network_ipv6_socket_address_t;

typedef struct wasi_sockets_network_ip_socket_address_t {
  uint8_t tag;
  union {
    wasi_sockets_network_ipv4_socket_address_t     ipv4;
    wasi_sockets_network_ipv6_socket_address_t     ipv6;
  } val;
} wasi_sockets_network_ip_socket_address_t;

#define WASI_SOCKETS_NETWORK_IP_SOCKET_ADDRESS_IPV4 0
#define WASI_SOCKETS_NETWORK_IP_SOCKET_ADDRESS_IPV6 1

typedef wasi_sockets_network_own_network_t wasi_sockets_instance_network_own_network_t;

typedef wasi_sockets_network_error_code_t wasi_sockets_udp_error_code_t;

typedef wasi_sockets_network_ip_socket_address_t wasi_sockets_udp_ip_socket_address_t;

typedef wasi_sockets_network_ip_address_family_t wasi_sockets_udp_ip_address_family_t;

typedef struct wasi_sockets_udp_incoming_datagram_t {
  format_plugin_list_u8_t   data;
  wasi_sockets_udp_ip_socket_address_t   remote_address;
} wasi_sockets_udp_incoming_datagram_t;

typedef struct {
  bool is_some;
  wasi_sockets_udp_ip_socket_address_t val;
} wasi_sockets_udp_option_ip_socket_address_t;

typedef struct wasi_sockets_udp_outgoing_datagram_t {
  format_plugin_list_u8_t   data;
  wasi_sockets_udp_option_ip_socket_address_t   remote_address;
} wasi_sockets_udp_outgoing_datagram_t;

typedef struct wasi_sockets_udp_own_udp_socket_t {
  int32_t __handle;
} wasi_sockets_udp_own_udp_socket_t;

typedef struct wasi_sockets_udp_borrow_udp_socket_t {
  int32_t __handle;
} wasi_sockets_udp_borrow_udp_socket_t;

typedef struct wasi_sockets_udp_own_incoming_datagram_stream_t {
  int32_t __handle;
} wasi_sockets_udp_own_incoming_datagram_stream_t;

typedef struct wasi_sockets_udp_borrow_incoming_datagram_stream_t {
  int32_t __handle;
} wasi_sockets_udp_borrow_incoming_datagram_stream_t;

typedef struct wasi_sockets_udp_own_outgoing_datagram_stream_t {
  int32_t __handle;
} wasi_sockets_udp_own_outgoing_datagram_stream_t;

typedef struct wasi_sockets_udp_borrow_outgoing_datagram_stream_t {
  int32_t __handle;
} wasi_sockets_udp_borrow_outgoing_datagram_stream_t;

typedef wasi_sockets_network_borrow_network_t wasi_sockets_udp_borrow_network_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_udp_error_code_t err;
  } val;
} wasi_sockets_udp_result_void_error_code_t;

typedef struct {
  wasi_sockets_udp_own_incoming_datagram_stream_t f0;
  wasi_sockets_udp_own_outgoing_datagram_stream_t f1;
} wasi_sockets_udp_tuple2_own_incoming_datagram_stream_own_outgoing_datagram_stream_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_udp_tuple2_own_incoming_datagram_stream_own_outgoing_datagram_stream_t ok;
    wasi_sockets_udp_error_code_t err;
  } val;
} wasi_sockets_udp_result_tuple2_own_incoming_datagram_stream_own_outgoing_datagram_stream_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_udp_ip_socket_address_t ok;
    wasi_sockets_udp_error_code_t err;
  } val;
} wasi_sockets_udp_result_ip_socket_address_error_code_t;

typedef struct {
  bool is_err;
  union {
    uint8_t ok;
    wasi_sockets_udp_error_code_t err;
  } val;
} wasi_sockets_udp_result_u8_error_code_t;

typedef struct {
  bool is_err;
  union {
    uint64_t ok;
    wasi_sockets_udp_error_code_t err;
  } val;
} wasi_sockets_udp_result_u64_error_code_t;

typedef wasi_io_poll_own_pollable_t wasi_sockets_udp_own_pollable_t;

typedef struct {
  wasi_sockets_udp_incoming_datagram_t *ptr;
  size_t len;
} wasi_sockets_udp_list_incoming_datagram_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_udp_list_incoming_datagram_t ok;
    wasi_sockets_udp_error_code_t err;
  } val;
} wasi_sockets_udp_result_list_incoming_datagram_error_code_t;

typedef struct {
  wasi_sockets_udp_outgoing_datagram_t *ptr;
  size_t len;
} wasi_sockets_udp_list_outgoing_datagram_t;

typedef wasi_sockets_network_error_code_t wasi_sockets_udp_create_socket_error_code_t;

typedef wasi_sockets_network_ip_address_family_t wasi_sockets_udp_create_socket_ip_address_family_t;

typedef wasi_sockets_udp_own_udp_socket_t wasi_sockets_udp_create_socket_own_udp_socket_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_udp_create_socket_own_udp_socket_t ok;
    wasi_sockets_udp_create_socket_error_code_t err;
  } val;
} wasi_sockets_udp_create_socket_result_own_udp_socket_error_code_t;

typedef wasi_clocks_monotonic_clock_duration_t wasi_sockets_tcp_duration_t;

typedef wasi_sockets_network_error_code_t wasi_sockets_tcp_error_code_t;

typedef wasi_sockets_network_ip_socket_address_t wasi_sockets_tcp_ip_socket_address_t;

typedef wasi_sockets_network_ip_address_family_t wasi_sockets_tcp_ip_address_family_t;

typedef uint8_t wasi_sockets_tcp_shutdown_type_t;

#define WASI_SOCKETS_TCP_SHUTDOWN_TYPE_RECEIVE 0
#define WASI_SOCKETS_TCP_SHUTDOWN_TYPE_SEND 1
#define WASI_SOCKETS_TCP_SHUTDOWN_TYPE_BOTH 2

typedef struct wasi_sockets_tcp_own_tcp_socket_t {
  int32_t __handle;
} wasi_sockets_tcp_own_tcp_socket_t;

typedef struct wasi_sockets_tcp_borrow_tcp_socket_t {
  int32_t __handle;
} wasi_sockets_tcp_borrow_tcp_socket_t;

typedef wasi_sockets_network_borrow_network_t wasi_sockets_tcp_borrow_network_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_tcp_error_code_t err;
  } val;
} wasi_sockets_tcp_result_void_error_code_t;

typedef wasi_io_streams_own_input_stream_t wasi_sockets_tcp_own_input_stream_t;

typedef wasi_io_streams_own_output_stream_t wasi_sockets_tcp_own_output_stream_t;

typedef struct {
  wasi_sockets_tcp_own_input_stream_t f0;
  wasi_sockets_tcp_own_output_stream_t f1;
} wasi_sockets_tcp_tuple2_own_input_stream_own_output_stream_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_tcp_tuple2_own_input_stream_own_output_stream_t ok;
    wasi_sockets_tcp_error_code_t err;
  } val;
} wasi_sockets_tcp_result_tuple2_own_input_stream_own_output_stream_error_code_t;

typedef struct {
  wasi_sockets_tcp_own_tcp_socket_t f0;
  wasi_sockets_tcp_own_input_stream_t f1;
  wasi_sockets_tcp_own_output_stream_t f2;
} wasi_sockets_tcp_tuple3_own_tcp_socket_own_input_stream_own_output_stream_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_tcp_tuple3_own_tcp_socket_own_input_stream_own_output_stream_t ok;
    wasi_sockets_tcp_error_code_t err;
  } val;
} wasi_sockets_tcp_result_tuple3_own_tcp_socket_own_input_stream_own_output_stream_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_tcp_ip_socket_address_t ok;
    wasi_sockets_tcp_error_code_t err;
  } val;
} wasi_sockets_tcp_result_ip_socket_address_error_code_t;

typedef struct {
  bool is_err;
  union {
    bool ok;
    wasi_sockets_tcp_error_code_t err;
  } val;
} wasi_sockets_tcp_result_bool_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_tcp_duration_t ok;
    wasi_sockets_tcp_error_code_t err;
  } val;
} wasi_sockets_tcp_result_duration_error_code_t;

typedef struct {
  bool is_err;
  union {
    uint32_t ok;
    wasi_sockets_tcp_error_code_t err;
  } val;
} wasi_sockets_tcp_result_u32_error_code_t;

typedef struct {
  bool is_err;
  union {
    uint8_t ok;
    wasi_sockets_tcp_error_code_t err;
  } val;
} wasi_sockets_tcp_result_u8_error_code_t;

typedef struct {
  bool is_err;
  union {
    uint64_t ok;
    wasi_sockets_tcp_error_code_t err;
  } val;
} wasi_sockets_tcp_result_u64_error_code_t;

typedef wasi_io_poll_own_pollable_t wasi_sockets_tcp_own_pollable_t;

typedef wasi_sockets_network_error_code_t wasi_sockets_tcp_create_socket_error_code_t;

typedef wasi_sockets_network_ip_address_family_t wasi_sockets_tcp_create_socket_ip_address_family_t;

typedef wasi_sockets_tcp_own_tcp_socket_t wasi_sockets_tcp_create_socket_own_tcp_socket_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_tcp_create_socket_own_tcp_socket_t ok;
    wasi_sockets_tcp_create_socket_error_code_t err;
  } val;
} wasi_sockets_tcp_create_socket_result_own_tcp_socket_error_code_t;

typedef wasi_sockets_network_error_code_t wasi_sockets_ip_name_lookup_error_code_t;

typedef wasi_sockets_network_ip_address_t wasi_sockets_ip_name_lookup_ip_address_t;

typedef struct wasi_sockets_ip_name_lookup_own_resolve_address_stream_t {
  int32_t __handle;
} wasi_sockets_ip_name_lookup_own_resolve_address_stream_t;

typedef struct wasi_sockets_ip_name_lookup_borrow_resolve_address_stream_t {
  int32_t __handle;
} wasi_sockets_ip_name_lookup_borrow_resolve_address_stream_t;

typedef struct {
  bool is_some;
  wasi_sockets_ip_name_lookup_ip_address_t val;
} wasi_sockets_ip_name_lookup_option_ip_address_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_ip_name_lookup_option_ip_address_t ok;
    wasi_sockets_ip_name_lookup_error_code_t err;
  } val;
} wasi_sockets_ip_name_lookup_result_option_ip_address_error_code_t;

typedef wasi_io_poll_own_pollable_t wasi_sockets_ip_name_lookup_own_pollable_t;

typedef wasi_sockets_network_borrow_network_t wasi_sockets_ip_name_lookup_borrow_network_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_ip_name_lookup_own_resolve_address_stream_t ok;
    wasi_sockets_ip_name_lookup_error_code_t err;
  } val;
} wasi_sockets_ip_name_lookup_result_own_resolve_address_stream_error_code_t;

typedef struct {
  uint64_t f0;
  uint64_t f1;
} format_plugin_tuple2_u64_u64_t;

// 日誌層級（syslog 七級）
typedef uint8_t local_log_process_pipeline_process_log_level_t;

#define LOCAL_LOG_PROCESS_PIPELINE_PROCESS_LOG_LEVEL_DEBUG 0
#define LOCAL_LOG_PROCESS_PIPELINE_PROCESS_LOG_LEVEL_INFO 1
#define LOCAL_LOG_PROCESS_PIPELINE_PROCESS_LOG_LEVEL_WARN 2
#define LOCAL_LOG_PROCESS_PIPELINE_PROCESS_LOG_LEVEL_ERROR 3
#define LOCAL_LOG_PROCESS_PIPELINE_PROCESS_LOG_LEVEL_CRIT 4
#define LOCAL_LOG_PROCESS_PIPELINE_PROCESS_LOG_LEVEL_ALERT 5
#define LOCAL_LOG_PROCESS_PIPELINE_PROCESS_LOG_LEVEL_EMERG 6

// parser 回傳的原始解析結果，不含 id
// host 收到後統一分配 id，轉換為 log-entry，再傳入後續插件
typedef struct local_log_process_pipeline_process_parsed_entry_t {
  format_plugin_string_t   timestamp;
  local_log_process_pipeline_process_log_level_t   level;
  format_plugin_string_t   message;
  format_plugin_list_tuple2_string_string_t   tags;
} local_log_process_pipeline_process_parsed_entry_t;

// 帶有 host 分配 id 的完整條目
// id 由 host 保證在同一批次內唯一，插件不得修改 id
typedef struct local_log_process_pipeline_process_log_entry_t {
  uint64_t   id;
  format_plugin_string_t   timestamp;
  local_log_process_pipeline_process_log_level_t   level;
  format_plugin_string_t   message;
  format_plugin_list_tuple2_string_string_t   tags;
} local_log_process_pipeline_process_log_entry_t;

// ── 錯誤型別 ──────────────────────────────
// parser 專屬錯誤，語意比通用錯誤更精確
typedef struct local_log_process_pipeline_process_parse_error_t {
  uint8_t tag;
  union {
    format_plugin_string_t     invalid_format;
    uint16_t     unsupported_version;
  } val;
} local_log_process_pipeline_process_parse_error_t;

#define LOCAL_LOG_PROCESS_PIPELINE_PROCESS_PARSE_ERROR_INVALID_FORMAT 0
#define LOCAL_LOG_PROCESS_PIPELINE_PROCESS_PARSE_ERROR_UNSUPPORTED_VERSION 1
#define LOCAL_LOG_PROCESS_PIPELINE_PROCESS_PARSE_ERROR_CORRUPTED_DATA 2

// 所有插件共用的通用錯誤
typedef struct local_log_process_pipeline_process_plugin_error_t {
  uint8_t tag;
  union {
    format_plugin_string_t     invalid_input;
    format_plugin_string_t     processing_failed;
    format_plugin_string_t     config_error;
    uint64_t     unknown_id;
  } val;
} local_log_process_pipeline_process_plugin_error_t;

#define LOCAL_LOG_PROCESS_PIPELINE_PROCESS_PLUGIN_ERROR_INVALID_INPUT 0
#define LOCAL_LOG_PROCESS_PIPELINE_PROCESS_PLUGIN_ERROR_PROCESSING_FAILED 1
#define LOCAL_LOG_PROCESS_PIPELINE_PROCESS_PLUGIN_ERROR_CONFIG_ERROR 2
// 插件回傳了輸入中不存在的 id，host 應視為嚴重錯誤
#define LOCAL_LOG_PROCESS_PIPELINE_PROCESS_PLUGIN_ERROR_UNKNOWN_ID 3
#define LOCAL_LOG_PROCESS_PIPELINE_PROCESS_PLUGIN_ERROR_INTERNAL_ERROR 4

// ── id 配對結果型別 ────────────────────────
// 插件只回傳「決策」，host 負責對原始 log-entry 執行實際操作
// 這確保原始資料不被插件修改（masking-plugin 是唯一例外）
// reduction-plugin 使用
typedef struct local_log_process_pipeline_process_filter_result_t {
  uint64_t   id;
  bool   keep;
} local_log_process_pipeline_process_filter_result_t;

// enricher-plugin 使用
typedef struct local_log_process_pipeline_process_enrich_result_t {
  uint64_t   id;
  // 要附加到對應 log-entry.tags 的額外標籤
  format_plugin_list_tuple2_string_string_t   additional_tags;
} local_log_process_pipeline_process_enrich_result_t;

// route-plugin 使用
typedef struct local_log_process_pipeline_process_route_result_t {
  uint64_t   id;
  // 此條 log 的轉送目標 URL 列表
  // 空 list 表示不轉送（由插件主動決定跳過）
  format_plugin_list_string_t   urls;
} local_log_process_pipeline_process_route_result_t;

typedef local_log_process_pipeline_process_log_entry_t format_plugin_log_entry_t;

typedef local_log_process_pipeline_process_plugin_error_t format_plugin_plugin_error_t;

typedef struct {
  format_plugin_log_entry_t *ptr;
  size_t len;
} format_plugin_list_log_entry_t;

typedef struct {
  format_plugin_list_u8_t *ptr;
  size_t len;
} format_plugin_list_list_u8_t;

typedef struct {
  bool is_err;
  union {
    format_plugin_list_list_u8_t ok;
    format_plugin_plugin_error_t err;
  } val;
} format_plugin_result_list_list_u8_plugin_error_t;

// Imported Functions from `wasi:cli/environment@0.2.0`
// Get the POSIX-style environment variables.
// 
// Each environment variable is provided as a pair of string variable names
// and string value.
// 
// Morally, these are a value import, but until value imports are available
// in the component model, this import function should return the same
// values each time it is called.
extern void wasi_cli_environment_get_environment(format_plugin_list_tuple2_string_string_t *ret);
// Get the POSIX-style arguments to the program.
extern void wasi_cli_environment_get_arguments(format_plugin_list_string_t *ret);
// Return a path that programs should use as their initial current working
// directory, interpreting `.` as shorthand for this.
extern bool wasi_cli_environment_initial_cwd(format_plugin_string_t *ret);

// Imported Functions from `wasi:cli/exit@0.2.0`
// Exit the current instance and any linked instances.
extern void wasi_cli_exit_exit(wasi_cli_exit_result_void_void_t *status);

// Imported Functions from `wasi:io/error@0.2.0`
extern void wasi_io_error_method_error_to_debug_string(wasi_io_error_borrow_error_t self, format_plugin_string_t *ret);

// Imported Functions from `wasi:io/poll@0.2.0`
extern bool wasi_io_poll_method_pollable_ready(wasi_io_poll_borrow_pollable_t self);
extern void wasi_io_poll_method_pollable_block(wasi_io_poll_borrow_pollable_t self);
extern void wasi_io_poll_poll(wasi_io_poll_list_borrow_pollable_t *in, format_plugin_list_u32_t *ret);

// Imported Functions from `wasi:io/streams@0.2.0`
extern bool wasi_io_streams_method_input_stream_read(wasi_io_streams_borrow_input_stream_t self, uint64_t len, format_plugin_list_u8_t *ret, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_input_stream_blocking_read(wasi_io_streams_borrow_input_stream_t self, uint64_t len, format_plugin_list_u8_t *ret, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_input_stream_skip(wasi_io_streams_borrow_input_stream_t self, uint64_t len, uint64_t *ret, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_input_stream_blocking_skip(wasi_io_streams_borrow_input_stream_t self, uint64_t len, uint64_t *ret, wasi_io_streams_stream_error_t *err);
extern wasi_io_streams_own_pollable_t wasi_io_streams_method_input_stream_subscribe(wasi_io_streams_borrow_input_stream_t self);
extern bool wasi_io_streams_method_output_stream_check_write(wasi_io_streams_borrow_output_stream_t self, uint64_t *ret, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_output_stream_write(wasi_io_streams_borrow_output_stream_t self, format_plugin_list_u8_t *contents, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_output_stream_blocking_write_and_flush(wasi_io_streams_borrow_output_stream_t self, format_plugin_list_u8_t *contents, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_output_stream_flush(wasi_io_streams_borrow_output_stream_t self, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_output_stream_blocking_flush(wasi_io_streams_borrow_output_stream_t self, wasi_io_streams_stream_error_t *err);
extern wasi_io_streams_own_pollable_t wasi_io_streams_method_output_stream_subscribe(wasi_io_streams_borrow_output_stream_t self);
extern bool wasi_io_streams_method_output_stream_write_zeroes(wasi_io_streams_borrow_output_stream_t self, uint64_t len, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_output_stream_blocking_write_zeroes_and_flush(wasi_io_streams_borrow_output_stream_t self, uint64_t len, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_output_stream_splice(wasi_io_streams_borrow_output_stream_t self, wasi_io_streams_borrow_input_stream_t src, uint64_t len, uint64_t *ret, wasi_io_streams_stream_error_t *err);
extern bool wasi_io_streams_method_output_stream_blocking_splice(wasi_io_streams_borrow_output_stream_t self, wasi_io_streams_borrow_input_stream_t src, uint64_t len, uint64_t *ret, wasi_io_streams_stream_error_t *err);

// Imported Functions from `wasi:cli/stdin@0.2.0`
extern wasi_cli_stdin_own_input_stream_t wasi_cli_stdin_get_stdin(void);

// Imported Functions from `wasi:cli/stdout@0.2.0`
extern wasi_cli_stdout_own_output_stream_t wasi_cli_stdout_get_stdout(void);

// Imported Functions from `wasi:cli/stderr@0.2.0`
extern wasi_cli_stderr_own_output_stream_t wasi_cli_stderr_get_stderr(void);

// Imported Functions from `wasi:cli/terminal-stdin@0.2.0`
// If stdin is connected to a terminal, return a `terminal-input` handle
// allowing further interaction with it.
extern bool wasi_cli_terminal_stdin_get_terminal_stdin(wasi_cli_terminal_stdin_own_terminal_input_t *ret);

// Imported Functions from `wasi:cli/terminal-stdout@0.2.0`
// If stdout is connected to a terminal, return a `terminal-output` handle
// allowing further interaction with it.
extern bool wasi_cli_terminal_stdout_get_terminal_stdout(wasi_cli_terminal_stdout_own_terminal_output_t *ret);

// Imported Functions from `wasi:cli/terminal-stderr@0.2.0`
// If stderr is connected to a terminal, return a `terminal-output` handle
// allowing further interaction with it.
extern bool wasi_cli_terminal_stderr_get_terminal_stderr(wasi_cli_terminal_stderr_own_terminal_output_t *ret);

// Imported Functions from `wasi:clocks/monotonic-clock@0.2.0`
extern wasi_clocks_monotonic_clock_instant_t wasi_clocks_monotonic_clock_now(void);
extern wasi_clocks_monotonic_clock_duration_t wasi_clocks_monotonic_clock_resolution(void);
extern wasi_clocks_monotonic_clock_own_pollable_t wasi_clocks_monotonic_clock_subscribe_instant(wasi_clocks_monotonic_clock_instant_t when);
extern wasi_clocks_monotonic_clock_own_pollable_t wasi_clocks_monotonic_clock_subscribe_duration(wasi_clocks_monotonic_clock_duration_t when);

// Imported Functions from `wasi:clocks/wall-clock@0.2.0`
extern void wasi_clocks_wall_clock_now(wasi_clocks_wall_clock_datetime_t *ret);
extern void wasi_clocks_wall_clock_resolution(wasi_clocks_wall_clock_datetime_t *ret);

// Imported Functions from `wasi:filesystem/types@0.2.0`
extern bool wasi_filesystem_types_method_descriptor_read_via_stream(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_filesize_t offset, wasi_filesystem_types_own_input_stream_t *ret, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_write_via_stream(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_filesize_t offset, wasi_filesystem_types_own_output_stream_t *ret, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_append_via_stream(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_own_output_stream_t *ret, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_advise(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_filesize_t offset, wasi_filesystem_types_filesize_t length, wasi_filesystem_types_advice_t advice, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_sync_data(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_get_flags(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_descriptor_flags_t *ret, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_get_type(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_descriptor_type_t *ret, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_set_size(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_filesize_t size, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_set_times(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_new_timestamp_t *data_access_timestamp, wasi_filesystem_types_new_timestamp_t *data_modification_timestamp, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_read(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_filesize_t length, wasi_filesystem_types_filesize_t offset, format_plugin_tuple2_list_u8_bool_t *ret, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_write(wasi_filesystem_types_borrow_descriptor_t self, format_plugin_list_u8_t *buffer, wasi_filesystem_types_filesize_t offset, wasi_filesystem_types_filesize_t *ret, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_read_directory(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_own_directory_entry_stream_t *ret, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_sync(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_create_directory_at(wasi_filesystem_types_borrow_descriptor_t self, format_plugin_string_t *path, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_stat(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_descriptor_stat_t *ret, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_stat_at(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_path_flags_t path_flags, format_plugin_string_t *path, wasi_filesystem_types_descriptor_stat_t *ret, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_set_times_at(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_path_flags_t path_flags, format_plugin_string_t *path, wasi_filesystem_types_new_timestamp_t *data_access_timestamp, wasi_filesystem_types_new_timestamp_t *data_modification_timestamp, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_link_at(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_path_flags_t old_path_flags, format_plugin_string_t *old_path, wasi_filesystem_types_borrow_descriptor_t new_descriptor, format_plugin_string_t *new_path, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_open_at(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_path_flags_t path_flags, format_plugin_string_t *path, wasi_filesystem_types_open_flags_t open_flags, wasi_filesystem_types_descriptor_flags_t flags, wasi_filesystem_types_own_descriptor_t *ret, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_readlink_at(wasi_filesystem_types_borrow_descriptor_t self, format_plugin_string_t *path, format_plugin_string_t *ret, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_remove_directory_at(wasi_filesystem_types_borrow_descriptor_t self, format_plugin_string_t *path, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_rename_at(wasi_filesystem_types_borrow_descriptor_t self, format_plugin_string_t *old_path, wasi_filesystem_types_borrow_descriptor_t new_descriptor, format_plugin_string_t *new_path, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_symlink_at(wasi_filesystem_types_borrow_descriptor_t self, format_plugin_string_t *old_path, format_plugin_string_t *new_path, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_unlink_file_at(wasi_filesystem_types_borrow_descriptor_t self, format_plugin_string_t *path, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_is_same_object(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_borrow_descriptor_t other);
extern bool wasi_filesystem_types_method_descriptor_metadata_hash(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_metadata_hash_value_t *ret, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_descriptor_metadata_hash_at(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_path_flags_t path_flags, format_plugin_string_t *path, wasi_filesystem_types_metadata_hash_value_t *ret, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_method_directory_entry_stream_read_directory_entry(wasi_filesystem_types_borrow_directory_entry_stream_t self, wasi_filesystem_types_option_directory_entry_t *ret, wasi_filesystem_types_error_code_t *err);
extern bool wasi_filesystem_types_filesystem_error_code(wasi_filesystem_types_borrow_error_t err_, wasi_filesystem_types_error_code_t *ret);

// Imported Functions from `wasi:filesystem/preopens@0.2.0`
extern void wasi_filesystem_preopens_get_directories(wasi_filesystem_preopens_list_tuple2_own_descriptor_string_t *ret);

// Imported Functions from `wasi:sockets/instance-network@0.2.0`
extern wasi_sockets_instance_network_own_network_t wasi_sockets_instance_network_instance_network(void);

// Imported Functions from `wasi:sockets/udp@0.2.0`
extern bool wasi_sockets_udp_method_udp_socket_start_bind(wasi_sockets_udp_borrow_udp_socket_t self, wasi_sockets_udp_borrow_network_t network, wasi_sockets_udp_ip_socket_address_t *local_address, wasi_sockets_udp_error_code_t *err);
extern bool wasi_sockets_udp_method_udp_socket_finish_bind(wasi_sockets_udp_borrow_udp_socket_t self, wasi_sockets_udp_error_code_t *err);
extern bool wasi_sockets_udp_method_udp_socket_stream(wasi_sockets_udp_borrow_udp_socket_t self, wasi_sockets_udp_ip_socket_address_t *maybe_remote_address, wasi_sockets_udp_tuple2_own_incoming_datagram_stream_own_outgoing_datagram_stream_t *ret, wasi_sockets_udp_error_code_t *err);
extern bool wasi_sockets_udp_method_udp_socket_local_address(wasi_sockets_udp_borrow_udp_socket_t self, wasi_sockets_udp_ip_socket_address_t *ret, wasi_sockets_udp_error_code_t *err);
extern bool wasi_sockets_udp_method_udp_socket_remote_address(wasi_sockets_udp_borrow_udp_socket_t self, wasi_sockets_udp_ip_socket_address_t *ret, wasi_sockets_udp_error_code_t *err);
extern wasi_sockets_udp_ip_address_family_t wasi_sockets_udp_method_udp_socket_address_family(wasi_sockets_udp_borrow_udp_socket_t self);
extern bool wasi_sockets_udp_method_udp_socket_unicast_hop_limit(wasi_sockets_udp_borrow_udp_socket_t self, uint8_t *ret, wasi_sockets_udp_error_code_t *err);
extern bool wasi_sockets_udp_method_udp_socket_set_unicast_hop_limit(wasi_sockets_udp_borrow_udp_socket_t self, uint8_t value, wasi_sockets_udp_error_code_t *err);
extern bool wasi_sockets_udp_method_udp_socket_receive_buffer_size(wasi_sockets_udp_borrow_udp_socket_t self, uint64_t *ret, wasi_sockets_udp_error_code_t *err);
extern bool wasi_sockets_udp_method_udp_socket_set_receive_buffer_size(wasi_sockets_udp_borrow_udp_socket_t self, uint64_t value, wasi_sockets_udp_error_code_t *err);
extern bool wasi_sockets_udp_method_udp_socket_send_buffer_size(wasi_sockets_udp_borrow_udp_socket_t self, uint64_t *ret, wasi_sockets_udp_error_code_t *err);
extern bool wasi_sockets_udp_method_udp_socket_set_send_buffer_size(wasi_sockets_udp_borrow_udp_socket_t self, uint64_t value, wasi_sockets_udp_error_code_t *err);
extern wasi_sockets_udp_own_pollable_t wasi_sockets_udp_method_udp_socket_subscribe(wasi_sockets_udp_borrow_udp_socket_t self);
extern bool wasi_sockets_udp_method_incoming_datagram_stream_receive(wasi_sockets_udp_borrow_incoming_datagram_stream_t self, uint64_t max_results, wasi_sockets_udp_list_incoming_datagram_t *ret, wasi_sockets_udp_error_code_t *err);
extern wasi_sockets_udp_own_pollable_t wasi_sockets_udp_method_incoming_datagram_stream_subscribe(wasi_sockets_udp_borrow_incoming_datagram_stream_t self);
extern bool wasi_sockets_udp_method_outgoing_datagram_stream_check_send(wasi_sockets_udp_borrow_outgoing_datagram_stream_t self, uint64_t *ret, wasi_sockets_udp_error_code_t *err);
extern bool wasi_sockets_udp_method_outgoing_datagram_stream_send(wasi_sockets_udp_borrow_outgoing_datagram_stream_t self, wasi_sockets_udp_list_outgoing_datagram_t *datagrams, uint64_t *ret, wasi_sockets_udp_error_code_t *err);
extern wasi_sockets_udp_own_pollable_t wasi_sockets_udp_method_outgoing_datagram_stream_subscribe(wasi_sockets_udp_borrow_outgoing_datagram_stream_t self);

// Imported Functions from `wasi:sockets/udp-create-socket@0.2.0`
extern bool wasi_sockets_udp_create_socket_create_udp_socket(wasi_sockets_udp_create_socket_ip_address_family_t address_family, wasi_sockets_udp_create_socket_own_udp_socket_t *ret, wasi_sockets_udp_create_socket_error_code_t *err);

// Imported Functions from `wasi:sockets/tcp@0.2.0`
extern bool wasi_sockets_tcp_method_tcp_socket_start_bind(wasi_sockets_tcp_borrow_tcp_socket_t self, wasi_sockets_tcp_borrow_network_t network, wasi_sockets_tcp_ip_socket_address_t *local_address, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_finish_bind(wasi_sockets_tcp_borrow_tcp_socket_t self, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_start_connect(wasi_sockets_tcp_borrow_tcp_socket_t self, wasi_sockets_tcp_borrow_network_t network, wasi_sockets_tcp_ip_socket_address_t *remote_address, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_finish_connect(wasi_sockets_tcp_borrow_tcp_socket_t self, wasi_sockets_tcp_tuple2_own_input_stream_own_output_stream_t *ret, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_start_listen(wasi_sockets_tcp_borrow_tcp_socket_t self, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_finish_listen(wasi_sockets_tcp_borrow_tcp_socket_t self, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_accept(wasi_sockets_tcp_borrow_tcp_socket_t self, wasi_sockets_tcp_tuple3_own_tcp_socket_own_input_stream_own_output_stream_t *ret, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_local_address(wasi_sockets_tcp_borrow_tcp_socket_t self, wasi_sockets_tcp_ip_socket_address_t *ret, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_remote_address(wasi_sockets_tcp_borrow_tcp_socket_t self, wasi_sockets_tcp_ip_socket_address_t *ret, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_is_listening(wasi_sockets_tcp_borrow_tcp_socket_t self);
extern wasi_sockets_tcp_ip_address_family_t wasi_sockets_tcp_method_tcp_socket_address_family(wasi_sockets_tcp_borrow_tcp_socket_t self);
extern bool wasi_sockets_tcp_method_tcp_socket_set_listen_backlog_size(wasi_sockets_tcp_borrow_tcp_socket_t self, uint64_t value, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_keep_alive_enabled(wasi_sockets_tcp_borrow_tcp_socket_t self, bool *ret, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_set_keep_alive_enabled(wasi_sockets_tcp_borrow_tcp_socket_t self, bool value, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_keep_alive_idle_time(wasi_sockets_tcp_borrow_tcp_socket_t self, wasi_sockets_tcp_duration_t *ret, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_set_keep_alive_idle_time(wasi_sockets_tcp_borrow_tcp_socket_t self, wasi_sockets_tcp_duration_t value, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_keep_alive_interval(wasi_sockets_tcp_borrow_tcp_socket_t self, wasi_sockets_tcp_duration_t *ret, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_set_keep_alive_interval(wasi_sockets_tcp_borrow_tcp_socket_t self, wasi_sockets_tcp_duration_t value, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_keep_alive_count(wasi_sockets_tcp_borrow_tcp_socket_t self, uint32_t *ret, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_set_keep_alive_count(wasi_sockets_tcp_borrow_tcp_socket_t self, uint32_t value, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_hop_limit(wasi_sockets_tcp_borrow_tcp_socket_t self, uint8_t *ret, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_set_hop_limit(wasi_sockets_tcp_borrow_tcp_socket_t self, uint8_t value, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_receive_buffer_size(wasi_sockets_tcp_borrow_tcp_socket_t self, uint64_t *ret, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_set_receive_buffer_size(wasi_sockets_tcp_borrow_tcp_socket_t self, uint64_t value, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_send_buffer_size(wasi_sockets_tcp_borrow_tcp_socket_t self, uint64_t *ret, wasi_sockets_tcp_error_code_t *err);
extern bool wasi_sockets_tcp_method_tcp_socket_set_send_buffer_size(wasi_sockets_tcp_borrow_tcp_socket_t self, uint64_t value, wasi_sockets_tcp_error_code_t *err);
extern wasi_sockets_tcp_own_pollable_t wasi_sockets_tcp_method_tcp_socket_subscribe(wasi_sockets_tcp_borrow_tcp_socket_t self);
extern bool wasi_sockets_tcp_method_tcp_socket_shutdown(wasi_sockets_tcp_borrow_tcp_socket_t self, wasi_sockets_tcp_shutdown_type_t shutdown_type, wasi_sockets_tcp_error_code_t *err);

// Imported Functions from `wasi:sockets/tcp-create-socket@0.2.0`
extern bool wasi_sockets_tcp_create_socket_create_tcp_socket(wasi_sockets_tcp_create_socket_ip_address_family_t address_family, wasi_sockets_tcp_create_socket_own_tcp_socket_t *ret, wasi_sockets_tcp_create_socket_error_code_t *err);

// Imported Functions from `wasi:sockets/ip-name-lookup@0.2.0`
extern bool wasi_sockets_ip_name_lookup_method_resolve_address_stream_resolve_next_address(wasi_sockets_ip_name_lookup_borrow_resolve_address_stream_t self, wasi_sockets_ip_name_lookup_option_ip_address_t *ret, wasi_sockets_ip_name_lookup_error_code_t *err);
extern wasi_sockets_ip_name_lookup_own_pollable_t wasi_sockets_ip_name_lookup_method_resolve_address_stream_subscribe(wasi_sockets_ip_name_lookup_borrow_resolve_address_stream_t self);
extern bool wasi_sockets_ip_name_lookup_resolve_addresses(wasi_sockets_ip_name_lookup_borrow_network_t network, format_plugin_string_t *name, wasi_sockets_ip_name_lookup_own_resolve_address_stream_t *ret, wasi_sockets_ip_name_lookup_error_code_t *err);

// Imported Functions from `wasi:random/random@0.2.0`
extern void wasi_random_random_get_random_bytes(uint64_t len, format_plugin_list_u8_t *ret);
extern uint64_t wasi_random_random_get_random_u64(void);

// Imported Functions from `wasi:random/insecure@0.2.0`
extern void wasi_random_insecure_get_insecure_random_bytes(uint64_t len, format_plugin_list_u8_t *ret);
extern uint64_t wasi_random_insecure_get_insecure_random_u64(void);

// Imported Functions from `wasi:random/insecure-seed@0.2.0`
extern void wasi_random_insecure_seed_insecure_seed(format_plugin_tuple2_u64_u64_t *ret);

// Exported Functions from `format-plugin`
bool exports_format_plugin_format(format_plugin_list_log_entry_t *struct_data, format_plugin_list_list_u8_t *ret, format_plugin_plugin_error_t *err);
uint64_t exports_format_plugin_report_usage(void);

// Helper Functions

void format_plugin_tuple2_string_string_free(format_plugin_tuple2_string_string_t *ptr);

void format_plugin_list_tuple2_string_string_free(format_plugin_list_tuple2_string_string_t *ptr);

void format_plugin_list_string_free(format_plugin_list_string_t *ptr);

void format_plugin_option_string_free(format_plugin_option_string_t *ptr);

void wasi_cli_exit_result_void_void_free(wasi_cli_exit_result_void_void_t *ptr);

extern void wasi_io_error_error_drop_own(wasi_io_error_own_error_t handle);

extern void wasi_io_error_error_drop_borrow(wasi_io_error_borrow_error_t handle);

extern wasi_io_error_borrow_error_t wasi_io_error_borrow_error(wasi_io_error_own_error_t handle);

extern void wasi_io_poll_pollable_drop_own(wasi_io_poll_own_pollable_t handle);

extern void wasi_io_poll_pollable_drop_borrow(wasi_io_poll_borrow_pollable_t handle);

extern wasi_io_poll_borrow_pollable_t wasi_io_poll_borrow_pollable(wasi_io_poll_own_pollable_t handle);

void wasi_io_poll_list_borrow_pollable_free(wasi_io_poll_list_borrow_pollable_t *ptr);

void format_plugin_list_u32_free(format_plugin_list_u32_t *ptr);

void wasi_io_streams_stream_error_free(wasi_io_streams_stream_error_t *ptr);

extern void wasi_io_streams_input_stream_drop_own(wasi_io_streams_own_input_stream_t handle);

extern void wasi_io_streams_input_stream_drop_borrow(wasi_io_streams_borrow_input_stream_t handle);

extern wasi_io_streams_borrow_input_stream_t wasi_io_streams_borrow_input_stream(wasi_io_streams_own_input_stream_t handle);

extern void wasi_io_streams_output_stream_drop_own(wasi_io_streams_own_output_stream_t handle);

extern void wasi_io_streams_output_stream_drop_borrow(wasi_io_streams_borrow_output_stream_t handle);

extern wasi_io_streams_borrow_output_stream_t wasi_io_streams_borrow_output_stream(wasi_io_streams_own_output_stream_t handle);

void format_plugin_list_u8_free(format_plugin_list_u8_t *ptr);

void wasi_io_streams_result_list_u8_stream_error_free(wasi_io_streams_result_list_u8_stream_error_t *ptr);

void wasi_io_streams_result_u64_stream_error_free(wasi_io_streams_result_u64_stream_error_t *ptr);

void wasi_io_streams_result_void_stream_error_free(wasi_io_streams_result_void_stream_error_t *ptr);

extern void wasi_cli_terminal_input_terminal_input_drop_own(wasi_cli_terminal_input_own_terminal_input_t handle);

extern void wasi_cli_terminal_input_terminal_input_drop_borrow(wasi_cli_terminal_input_borrow_terminal_input_t handle);

extern wasi_cli_terminal_input_borrow_terminal_input_t wasi_cli_terminal_input_borrow_terminal_input(wasi_cli_terminal_input_own_terminal_input_t handle);

extern void wasi_cli_terminal_output_terminal_output_drop_own(wasi_cli_terminal_output_own_terminal_output_t handle);

extern void wasi_cli_terminal_output_terminal_output_drop_borrow(wasi_cli_terminal_output_borrow_terminal_output_t handle);

extern wasi_cli_terminal_output_borrow_terminal_output_t wasi_cli_terminal_output_borrow_terminal_output(wasi_cli_terminal_output_own_terminal_output_t handle);

void wasi_cli_terminal_stdin_option_own_terminal_input_free(wasi_cli_terminal_stdin_option_own_terminal_input_t *ptr);

void wasi_cli_terminal_stdout_option_own_terminal_output_free(wasi_cli_terminal_stdout_option_own_terminal_output_t *ptr);

void wasi_cli_terminal_stderr_option_own_terminal_output_free(wasi_cli_terminal_stderr_option_own_terminal_output_t *ptr);

void wasi_filesystem_types_option_datetime_free(wasi_filesystem_types_option_datetime_t *ptr);

void wasi_filesystem_types_descriptor_stat_free(wasi_filesystem_types_descriptor_stat_t *ptr);

void wasi_filesystem_types_new_timestamp_free(wasi_filesystem_types_new_timestamp_t *ptr);

void wasi_filesystem_types_directory_entry_free(wasi_filesystem_types_directory_entry_t *ptr);

extern void wasi_filesystem_types_descriptor_drop_own(wasi_filesystem_types_own_descriptor_t handle);

extern void wasi_filesystem_types_descriptor_drop_borrow(wasi_filesystem_types_borrow_descriptor_t handle);

extern wasi_filesystem_types_borrow_descriptor_t wasi_filesystem_types_borrow_descriptor(wasi_filesystem_types_own_descriptor_t handle);

extern void wasi_filesystem_types_directory_entry_stream_drop_own(wasi_filesystem_types_own_directory_entry_stream_t handle);

extern void wasi_filesystem_types_directory_entry_stream_drop_borrow(wasi_filesystem_types_borrow_directory_entry_stream_t handle);

extern wasi_filesystem_types_borrow_directory_entry_stream_t wasi_filesystem_types_borrow_directory_entry_stream(wasi_filesystem_types_own_directory_entry_stream_t handle);

void wasi_filesystem_types_result_own_input_stream_error_code_free(wasi_filesystem_types_result_own_input_stream_error_code_t *ptr);

void wasi_filesystem_types_result_own_output_stream_error_code_free(wasi_filesystem_types_result_own_output_stream_error_code_t *ptr);

void wasi_filesystem_types_result_void_error_code_free(wasi_filesystem_types_result_void_error_code_t *ptr);

void wasi_filesystem_types_result_descriptor_flags_error_code_free(wasi_filesystem_types_result_descriptor_flags_error_code_t *ptr);

void wasi_filesystem_types_result_descriptor_type_error_code_free(wasi_filesystem_types_result_descriptor_type_error_code_t *ptr);

void wasi_filesystem_types_result_tuple2_list_u8_bool_error_code_free(wasi_filesystem_types_result_tuple2_list_u8_bool_error_code_t *ptr);

void wasi_filesystem_types_result_filesize_error_code_free(wasi_filesystem_types_result_filesize_error_code_t *ptr);

void wasi_filesystem_types_result_own_directory_entry_stream_error_code_free(wasi_filesystem_types_result_own_directory_entry_stream_error_code_t *ptr);

void wasi_filesystem_types_result_descriptor_stat_error_code_free(wasi_filesystem_types_result_descriptor_stat_error_code_t *ptr);

void wasi_filesystem_types_result_own_descriptor_error_code_free(wasi_filesystem_types_result_own_descriptor_error_code_t *ptr);

void wasi_filesystem_types_result_string_error_code_free(wasi_filesystem_types_result_string_error_code_t *ptr);

void wasi_filesystem_types_result_metadata_hash_value_error_code_free(wasi_filesystem_types_result_metadata_hash_value_error_code_t *ptr);

void wasi_filesystem_types_option_directory_entry_free(wasi_filesystem_types_option_directory_entry_t *ptr);

void wasi_filesystem_types_result_option_directory_entry_error_code_free(wasi_filesystem_types_result_option_directory_entry_error_code_t *ptr);

void wasi_filesystem_types_option_error_code_free(wasi_filesystem_types_option_error_code_t *ptr);

void wasi_filesystem_preopens_tuple2_own_descriptor_string_free(wasi_filesystem_preopens_tuple2_own_descriptor_string_t *ptr);

void wasi_filesystem_preopens_list_tuple2_own_descriptor_string_free(wasi_filesystem_preopens_list_tuple2_own_descriptor_string_t *ptr);

extern void wasi_sockets_network_network_drop_own(wasi_sockets_network_own_network_t handle);

extern void wasi_sockets_network_network_drop_borrow(wasi_sockets_network_borrow_network_t handle);

extern wasi_sockets_network_borrow_network_t wasi_sockets_network_borrow_network(wasi_sockets_network_own_network_t handle);

void wasi_sockets_network_ip_address_free(wasi_sockets_network_ip_address_t *ptr);

void wasi_sockets_network_ip_socket_address_free(wasi_sockets_network_ip_socket_address_t *ptr);

void wasi_sockets_udp_ip_socket_address_free(wasi_sockets_udp_ip_socket_address_t *ptr);

void wasi_sockets_udp_incoming_datagram_free(wasi_sockets_udp_incoming_datagram_t *ptr);

void wasi_sockets_udp_option_ip_socket_address_free(wasi_sockets_udp_option_ip_socket_address_t *ptr);

void wasi_sockets_udp_outgoing_datagram_free(wasi_sockets_udp_outgoing_datagram_t *ptr);

extern void wasi_sockets_udp_udp_socket_drop_own(wasi_sockets_udp_own_udp_socket_t handle);

extern void wasi_sockets_udp_udp_socket_drop_borrow(wasi_sockets_udp_borrow_udp_socket_t handle);

extern wasi_sockets_udp_borrow_udp_socket_t wasi_sockets_udp_borrow_udp_socket(wasi_sockets_udp_own_udp_socket_t handle);

extern void wasi_sockets_udp_incoming_datagram_stream_drop_own(wasi_sockets_udp_own_incoming_datagram_stream_t handle);

extern void wasi_sockets_udp_incoming_datagram_stream_drop_borrow(wasi_sockets_udp_borrow_incoming_datagram_stream_t handle);

extern wasi_sockets_udp_borrow_incoming_datagram_stream_t wasi_sockets_udp_borrow_incoming_datagram_stream(wasi_sockets_udp_own_incoming_datagram_stream_t handle);

extern void wasi_sockets_udp_outgoing_datagram_stream_drop_own(wasi_sockets_udp_own_outgoing_datagram_stream_t handle);

extern void wasi_sockets_udp_outgoing_datagram_stream_drop_borrow(wasi_sockets_udp_borrow_outgoing_datagram_stream_t handle);

extern wasi_sockets_udp_borrow_outgoing_datagram_stream_t wasi_sockets_udp_borrow_outgoing_datagram_stream(wasi_sockets_udp_own_outgoing_datagram_stream_t handle);

void wasi_sockets_udp_result_void_error_code_free(wasi_sockets_udp_result_void_error_code_t *ptr);

void wasi_sockets_udp_result_tuple2_own_incoming_datagram_stream_own_outgoing_datagram_stream_error_code_free(wasi_sockets_udp_result_tuple2_own_incoming_datagram_stream_own_outgoing_datagram_stream_error_code_t *ptr);

void wasi_sockets_udp_result_ip_socket_address_error_code_free(wasi_sockets_udp_result_ip_socket_address_error_code_t *ptr);

void wasi_sockets_udp_result_u8_error_code_free(wasi_sockets_udp_result_u8_error_code_t *ptr);

void wasi_sockets_udp_result_u64_error_code_free(wasi_sockets_udp_result_u64_error_code_t *ptr);

void wasi_sockets_udp_list_incoming_datagram_free(wasi_sockets_udp_list_incoming_datagram_t *ptr);

void wasi_sockets_udp_result_list_incoming_datagram_error_code_free(wasi_sockets_udp_result_list_incoming_datagram_error_code_t *ptr);

void wasi_sockets_udp_list_outgoing_datagram_free(wasi_sockets_udp_list_outgoing_datagram_t *ptr);

void wasi_sockets_udp_create_socket_result_own_udp_socket_error_code_free(wasi_sockets_udp_create_socket_result_own_udp_socket_error_code_t *ptr);

void wasi_sockets_tcp_ip_socket_address_free(wasi_sockets_tcp_ip_socket_address_t *ptr);

extern void wasi_sockets_tcp_tcp_socket_drop_own(wasi_sockets_tcp_own_tcp_socket_t handle);

extern void wasi_sockets_tcp_tcp_socket_drop_borrow(wasi_sockets_tcp_borrow_tcp_socket_t handle);

extern wasi_sockets_tcp_borrow_tcp_socket_t wasi_sockets_tcp_borrow_tcp_socket(wasi_sockets_tcp_own_tcp_socket_t handle);

void wasi_sockets_tcp_result_void_error_code_free(wasi_sockets_tcp_result_void_error_code_t *ptr);

void wasi_sockets_tcp_result_tuple2_own_input_stream_own_output_stream_error_code_free(wasi_sockets_tcp_result_tuple2_own_input_stream_own_output_stream_error_code_t *ptr);

void wasi_sockets_tcp_result_tuple3_own_tcp_socket_own_input_stream_own_output_stream_error_code_free(wasi_sockets_tcp_result_tuple3_own_tcp_socket_own_input_stream_own_output_stream_error_code_t *ptr);

void wasi_sockets_tcp_result_ip_socket_address_error_code_free(wasi_sockets_tcp_result_ip_socket_address_error_code_t *ptr);

void wasi_sockets_tcp_result_bool_error_code_free(wasi_sockets_tcp_result_bool_error_code_t *ptr);

void wasi_sockets_tcp_result_duration_error_code_free(wasi_sockets_tcp_result_duration_error_code_t *ptr);

void wasi_sockets_tcp_result_u32_error_code_free(wasi_sockets_tcp_result_u32_error_code_t *ptr);

void wasi_sockets_tcp_result_u8_error_code_free(wasi_sockets_tcp_result_u8_error_code_t *ptr);

void wasi_sockets_tcp_result_u64_error_code_free(wasi_sockets_tcp_result_u64_error_code_t *ptr);

void wasi_sockets_tcp_create_socket_result_own_tcp_socket_error_code_free(wasi_sockets_tcp_create_socket_result_own_tcp_socket_error_code_t *ptr);

void wasi_sockets_ip_name_lookup_ip_address_free(wasi_sockets_ip_name_lookup_ip_address_t *ptr);

extern void wasi_sockets_ip_name_lookup_resolve_address_stream_drop_own(wasi_sockets_ip_name_lookup_own_resolve_address_stream_t handle);

extern void wasi_sockets_ip_name_lookup_resolve_address_stream_drop_borrow(wasi_sockets_ip_name_lookup_borrow_resolve_address_stream_t handle);

extern wasi_sockets_ip_name_lookup_borrow_resolve_address_stream_t wasi_sockets_ip_name_lookup_borrow_resolve_address_stream(wasi_sockets_ip_name_lookup_own_resolve_address_stream_t handle);

void wasi_sockets_ip_name_lookup_option_ip_address_free(wasi_sockets_ip_name_lookup_option_ip_address_t *ptr);

void wasi_sockets_ip_name_lookup_result_option_ip_address_error_code_free(wasi_sockets_ip_name_lookup_result_option_ip_address_error_code_t *ptr);

void wasi_sockets_ip_name_lookup_result_own_resolve_address_stream_error_code_free(wasi_sockets_ip_name_lookup_result_own_resolve_address_stream_error_code_t *ptr);

void local_log_process_pipeline_process_parsed_entry_free(local_log_process_pipeline_process_parsed_entry_t *ptr);

void local_log_process_pipeline_process_log_entry_free(local_log_process_pipeline_process_log_entry_t *ptr);

void local_log_process_pipeline_process_parse_error_free(local_log_process_pipeline_process_parse_error_t *ptr);

void local_log_process_pipeline_process_plugin_error_free(local_log_process_pipeline_process_plugin_error_t *ptr);

void format_plugin_log_entry_free(format_plugin_log_entry_t *ptr);

void format_plugin_plugin_error_free(format_plugin_plugin_error_t *ptr);

void format_plugin_list_log_entry_free(format_plugin_list_log_entry_t *ptr);

void format_plugin_list_list_u8_free(format_plugin_list_list_u8_t *ptr);

void format_plugin_result_list_list_u8_plugin_error_free(format_plugin_result_list_list_u8_plugin_error_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void format_plugin_string_set(format_plugin_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void format_plugin_string_dup(format_plugin_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void format_plugin_string_dup_n(format_plugin_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void format_plugin_string_free(format_plugin_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
