// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ParserPluginWorld.wit.Imports.wasi.random.v0_2_0;

public interface IInsecureImports {

    public static unsafe byte[] GetInsecureRandomBytes(ulong len)
    {

        var retArea = stackalloc uint[3];
        var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
        InsecureImportsInterop.GetInsecureRandomBytesWasmInterop.wasmImportGetInsecureRandomBytes(unchecked((long)(len)), ptr);

        var array = new byte[new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0]];
        new global::System.Span<byte>((void*)(new global::System.Span<nint>((void*)((byte*)ptr + 0), 1)[0]), new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0]).CopyTo(new global::System.Span<byte>(array));

        if (new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0] > 0) {
            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)ptr + 0), 1)[0]);
        }
        return array;

    }

    public static unsafe ulong GetInsecureRandomU64()
    {
        var result =  InsecureImportsInterop.GetInsecureRandomU64WasmInterop.wasmImportGetInsecureRandomU64();
        return unchecked((ulong)(result));

    }

}
