// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ParserPluginWorld.wit.Imports.wasi.cli.v0_2_0;

public interface ITerminalStdinImports {

    public static unsafe global::ParserPluginWorld.wit.Imports.wasi.cli.v0_2_0.ITerminalInputImports.TerminalInput? GetTerminalStdin()
    {

        var retArea = stackalloc uint[3];
        var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
        TerminalStdinImportsInterop.GetTerminalStdinWasmInterop.wasmImportGetTerminalStdin(ptr);

        global::ParserPluginWorld.wit.Imports.wasi.cli.v0_2_0.ITerminalInputImports.TerminalInput? lifted;

        switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
            case 0: {
                lifted = null;
                break;
            }

            case 1: {
                var resource = new global::ParserPluginWorld.wit.Imports.wasi.cli.v0_2_0.ITerminalInputImports.TerminalInput(new global::ParserPluginWorld.wit.Imports.wasi.cli.v0_2_0.ITerminalInputImports.TerminalInput.THandle(new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0]));

                lifted = resource;
                break;
            }

            default: throw new global::System.ArgumentException("invalid discriminant: " + (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]));
        }
        return lifted;

    }

}
