// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ParserPluginWorld.wit.Imports.wasi.cli.v0_2_0;

public interface IExitImports {

    public static unsafe void Exit(Result<None, None> status)
    {

        int lowered;

        switch (status.Tag) {
            case 0: {

                lowered = 0;

                break;
            }
            case 1: {

                lowered = 1;

                break;
            }

            default: throw new global::System.ArgumentException("invalid discriminant: " + status);
        }
        ExitImportsInterop.ExitWasmInterop.wasmImportExit(lowered);

    }

}
