// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;

namespace ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0
{
    public static class UdpImportsInterop {

        internal static class UdpSocket
        {

            public static class StartBindWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[method]udp-socket.start-bind"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportStartBind(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, int p10, int p11, int p12, int p13, nint p14);
            }

            public static class FinishBindWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[method]udp-socket.finish-bind"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportFinishBind(int p0, nint p1);
            }

            public static class StreamWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[method]udp-socket.stream"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportStream(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, int p10, int p11, int p12, int p13, nint p14);
            }

            public static class LocalAddressWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[method]udp-socket.local-address"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportLocalAddress(int p0, nint p1);
            }

            public static class RemoteAddressWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[method]udp-socket.remote-address"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportRemoteAddress(int p0, nint p1);
            }

            public static class AddressFamilyWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[method]udp-socket.address-family"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern int wasmImportAddressFamily(int p0);
            }

            public static class UnicastHopLimitWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[method]udp-socket.unicast-hop-limit"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportUnicastHopLimit(int p0, nint p1);
            }

            public static class SetUnicastHopLimitWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[method]udp-socket.set-unicast-hop-limit"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportSetUnicastHopLimit(int p0, int p1, nint p2);
            }

            public static class ReceiveBufferSizeWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[method]udp-socket.receive-buffer-size"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportReceiveBufferSize(int p0, nint p1);
            }

            public static class SetReceiveBufferSizeWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[method]udp-socket.set-receive-buffer-size"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportSetReceiveBufferSize(int p0, long p1, nint p2);
            }

            public static class SendBufferSizeWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[method]udp-socket.send-buffer-size"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportSendBufferSize(int p0, nint p1);
            }

            public static class SetSendBufferSizeWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[method]udp-socket.set-send-buffer-size"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportSetSendBufferSize(int p0, long p1, nint p2);
            }

            public static class SubscribeWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[method]udp-socket.subscribe"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern int wasmImportSubscribe(int p0);
            }

        }

        internal static class IncomingDatagramStream
        {

            public static class ReceiveWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[method]incoming-datagram-stream.receive"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportReceive(int p0, long p1, nint p2);
            }

            public static class SubscribeWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[method]incoming-datagram-stream.subscribe"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern int wasmImportSubscribe(int p0);
            }

        }

        internal static class OutgoingDatagramStream
        {

            public static class CheckSendWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[method]outgoing-datagram-stream.check-send"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportCheckSend(int p0, nint p1);
            }

            public static class SendWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[method]outgoing-datagram-stream.send"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportSend(int p0, nint p1, int p2, nint p3);
            }

            public static class SubscribeWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/udp@0.2.0", EntryPoint = "[method]outgoing-datagram-stream.subscribe"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern int wasmImportSubscribe(int p0);
            }

        }

    }
}
