// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ParserPluginWorld.wit.Imports.local.logProcess.v0_3_0;

public interface IPipelineProcessImports {

    /**
    * 日誌層級（syslog 七級）
    */

    public enum LogLevel {
        DEBUG, INFO, WARN, ERROR, CRIT, ALERT, EMERG
    }

    /**
    * parser 回傳的原始解析結果，不含 id
    * host 收到後統一分配 id，轉換為 log-entry，再傳入後續插件
    */

    public struct ParsedEntry {
        public string timestamp;
        public LogLevel level;
        public string message;
        public global::System.Collections.Generic.List<(string, string)> tags;
        public string targettag;

        public ParsedEntry(string timestamp, LogLevel level, string message, global::System.Collections.Generic.List<(string, string)> tags, string targettag) {
            this.timestamp = timestamp;
            this.level = level;
            this.message = message;
            this.tags = tags;
            this.targettag = targettag;
        }
    }

    /**
    * 帶有 host 分配 id 的完整條目
    * id 由 host 保證在同一批次內唯一，插件不得修改 id
    */

    public struct LogEntry {
        public ulong id;
        public string timestamp;
        public LogLevel level;
        public string message;
        public global::System.Collections.Generic.List<(string, string)> tags;

        public LogEntry(ulong id, string timestamp, LogLevel level, string message, global::System.Collections.Generic.List<(string, string)> tags) {
            this.id = id;
            this.timestamp = timestamp;
            this.level = level;
            this.message = message;
            this.tags = tags;
        }
    }

    /**
    * ── 錯誤型別 ──────────────────────────────
    * parser 專屬錯誤，語意比通用錯誤更精確
    */

    public class ParseError {
        public readonly byte Tag;
        private readonly object? value;

        private ParseError(byte tag, object? value) {
            this.Tag = tag;
            this.value = value;
        }

        public static ParseError InvalidFormat(string invalidFormat) {
            return new ParseError(Tags.InvalidFormat, invalidFormat);
        }

        public static ParseError UnsupportedVersion(ushort unsupportedVersion) {
            return new ParseError(Tags.UnsupportedVersion, unsupportedVersion);
        }

        public static ParseError CorruptedData() {
            return new ParseError(Tags.CorruptedData, null);
        }

        public string AsInvalidFormat
        {
            get
            {
                if (Tag == Tags.InvalidFormat)
                return (string)value!;
                else
                throw new global::System.ArgumentException("expected InvalidFormat, got " + Tag);
            }
        }

        public ushort AsUnsupportedVersion
        {
            get
            {
                if (Tag == Tags.UnsupportedVersion)
                return (ushort)value!;
                else
                throw new global::System.ArgumentException("expected UnsupportedVersion, got " + Tag);
            }
        }

        public class Tags {
            public const byte InvalidFormat = 0;
            public const byte UnsupportedVersion = 1;
            public const byte CorruptedData = 2;
        }
    }

    /**
    * 所有插件共用的通用錯誤
    */

    public class PluginError {
        public readonly byte Tag;
        private readonly object? value;

        private PluginError(byte tag, object? value) {
            this.Tag = tag;
            this.value = value;
        }

        public static PluginError InvalidInput(string invalidInput) {
            return new PluginError(Tags.InvalidInput, invalidInput);
        }

        public static PluginError ProcessingFailed(string processingFailed) {
            return new PluginError(Tags.ProcessingFailed, processingFailed);
        }

        public static PluginError ConfigError(string configError) {
            return new PluginError(Tags.ConfigError, configError);
        }

        public static PluginError UnknownId(ulong unknownId) {
            return new PluginError(Tags.UnknownId, unknownId);
        }

        public static PluginError InternalError() {
            return new PluginError(Tags.InternalError, null);
        }

        public string AsInvalidInput
        {
            get
            {
                if (Tag == Tags.InvalidInput)
                return (string)value!;
                else
                throw new global::System.ArgumentException("expected InvalidInput, got " + Tag);
            }
        }

        public string AsProcessingFailed
        {
            get
            {
                if (Tag == Tags.ProcessingFailed)
                return (string)value!;
                else
                throw new global::System.ArgumentException("expected ProcessingFailed, got " + Tag);
            }
        }

        public string AsConfigError
        {
            get
            {
                if (Tag == Tags.ConfigError)
                return (string)value!;
                else
                throw new global::System.ArgumentException("expected ConfigError, got " + Tag);
            }
        }

        public ulong AsUnknownId
        {
            get
            {
                if (Tag == Tags.UnknownId)
                return (ulong)value!;
                else
                throw new global::System.ArgumentException("expected UnknownId, got " + Tag);
            }
        }

        public class Tags {
            public const byte InvalidInput = 0;
            public const byte ProcessingFailed = 1;
            public const byte ConfigError = 2;
            public const byte UnknownId = 3;
            public const byte InternalError = 4;
        }
    }

    /**
    * ── id 配對結果型別 ────────────────────────
    * 插件只回傳「決策」，host 負責對原始 log-entry 執行實際操作
    * 這確保原始資料不被插件修改（masking-plugin 是唯一例外）
    * reduction-plugin 使用
    */

    public struct FilterResult {
        public ulong id;
        public bool keep;

        public FilterResult(ulong id, bool keep) {
            this.id = id;
            this.keep = keep;
        }
    }

    /**
    * enricher-plugin 使用
    */

    public struct EnrichResult {
        public ulong id;
        public global::System.Collections.Generic.List<(string, string)> additionalTags;

        public EnrichResult(ulong id, global::System.Collections.Generic.List<(string, string)> additionalTags) {
            this.id = id;
            this.additionalTags = additionalTags;
        }
    }

    /**
    * route-plugin 使用
    */

    public struct RouteResult {
        public ulong id;
        public global::System.Collections.Generic.List<string> urls;

        public RouteResult(ulong id, global::System.Collections.Generic.List<string> urls) {
            this.id = id;
            this.urls = urls;
        }
    }

}
