// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;

namespace ParserPluginWorld.wit.Imports.wasi.filesystem.v0_2_0
{
    public static class PreopensImportsInterop {

        public static class GetDirectoriesWasmInterop
        {
            [global::System.Runtime.InteropServices.DllImportAttribute("wasi:filesystem/preopens@0.2.0", EntryPoint = "get-directories"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
            public static extern void wasmImportGetDirectories(nint p0);
        }

    }
}
