// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ParserPluginWorld.wit.Imports.wasi.cli.v0_2_0;

public interface IStdinImports {

    public static unsafe global::ParserPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.InputStream GetStdin()
    {
        var result =  StdinImportsInterop.GetStdinWasmInterop.wasmImportGetStdin();
        var resource = new global::ParserPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.InputStream(new global::ParserPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.InputStream.THandle(result));
        return resource;

    }

}
