// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;

namespace ParserPluginWorld.wit.Imports.wasi.cli.v0_2_0
{
    public static class TerminalInputImportsInterop {

        internal static class TerminalInput
        {

        }

    }
}
