// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ParserPluginWorld.wit.Imports.wasi.filesystem.v0_2_0;

public interface IPreopensImports {

    public static unsafe global::System.Collections.Generic.List<(global::ParserPluginWorld.wit.Imports.wasi.filesystem.v0_2_0.ITypesImports.Descriptor, string)> GetDirectories()
    {

        var retArea = stackalloc uint[3];
        var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
        PreopensImportsInterop.GetDirectoriesWasmInterop.wasmImportGetDirectories(ptr);

        var array = new global::System.Collections.Generic.List<(global::ParserPluginWorld.wit.Imports.wasi.filesystem.v0_2_0.ITypesImports.Descriptor, string)>(new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0]);
        for (int index = 0; index < new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0]; ++index) {
            nint basePtr = new global::System.Span<nint>((void*)((byte*)ptr + 0), 1)[0] + (index * 12);
            var resource = new global::ParserPluginWorld.wit.Imports.wasi.filesystem.v0_2_0.ITypesImports.Descriptor(new global::ParserPluginWorld.wit.Imports.wasi.filesystem.v0_2_0.ITypesImports.Descriptor.THandle(new global::System.Span<int>((void*)((byte*)basePtr + 0), 1)[0]));

            var str = global::System.Text.Encoding.UTF8.GetString((byte*)new global::System.Span<nint>((void*)((byte*)basePtr + 4), 1)[0], new global::System.Span<int>((void*)((byte*)basePtr + 8), 1)[0]);
            if (new global::System.Span<int>((void*)((byte*)basePtr + 8), 1)[0] > 0) {
                global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr + 4), 1)[0]);
            }

            array.Add((resource, str));
        }

        if (new global::System.Span<int>((void*)((byte*)ptr + 4), 1)[0] > 0) {
            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)ptr + 0), 1)[0]);
        }
        return array;

    }

}
