// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;

namespace ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0
{
    public static class IpNameLookupImportsInterop {

        internal static class ResolveAddressStream
        {

            public static class ResolveNextAddressWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/ip-name-lookup@0.2.0", EntryPoint = "[method]resolve-address-stream.resolve-next-address"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern void wasmImportResolveNextAddress(int p0, nint p1);
            }

            public static class SubscribeWasmInterop
            {
                [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/ip-name-lookup@0.2.0", EntryPoint = "[method]resolve-address-stream.subscribe"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
                public static extern int wasmImportSubscribe(int p0);
            }

        }

        public static class ResolveAddressesWasmInterop
        {
            [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/ip-name-lookup@0.2.0", EntryPoint = "resolve-addresses"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
            public static extern void wasmImportResolveAddresses(int p0, nint p1, int p2, nint p3);
        }

    }
}
