// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace ParserPluginWorld.wit.Imports.wasi.cli.v0_2_0;

public interface IStderrImports {

    public static unsafe global::ParserPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream GetStderr()
    {
        var result =  StderrImportsInterop.GetStderrWasmInterop.wasmImportGetStderr();
        var resource = new global::ParserPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream(new global::ParserPluginWorld.wit.Imports.wasi.io.v0_2_0.IStreamsImports.OutputStream.THandle(result));
        return resource;

    }

}
