// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;

namespace ParserPluginWorld.wit.Imports.wasi.sockets.v0_2_0
{
    public static class InstanceNetworkImportsInterop {

        public static class InstanceNetworkWasmInterop
        {
            [global::System.Runtime.InteropServices.DllImportAttribute("wasi:sockets/instance-network@0.2.0", EntryPoint = "instance-network"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
            public static extern int wasmImportInstanceNetwork();
        }

    }
}
