// Code generated by wit-bindgen-go. DO NOT EDIT.

package parserplugin

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// ParseErrorShape is used for storage in variant or result types.
type ParseErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(ParseError{})]byte
}
