// Code generated by wit-bindgen-go. DO NOT EDIT.

package parserplugin

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "local:log-process@0.2.0".

//go:wasmexport parse
//export parse
func wasmexport_Parse(rawData0 *string, rawData1 uint32) (result *cm.Result[ParseErrorShape, cm.List[ParsedEntry], ParseError]) {
	rawData := cm.LiftList[cm.List[string]]((*string)(rawData0), (uint32)(rawData1))
	result_ := Exports.Parse(rawData)
	result = &result_
	return
}

//go:wasmexport report-usage
//export report-usage
func wasmexport_ReportUsage() (result0 uint64) {
	result := Exports.ReportUsage()
	result0 = (uint64)(result)
	return
}

//go:wasmexport reset
//export reset
func wasmexport_Reset() {
	Exports.Reset()
}
