// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
#include "parser_plugin.h"
#include <stdlib.h>
#include <string.h>

// Exported Functions from `parser-plugin`

__attribute__((__weak__, __export_name__("cabi_post_parse")))
void __wasm_export_exports_parser_plugin_parse_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      size_t len0 = *((size_t*) (arg0 + (2*sizeof(void*))));
      if (len0 > 0) {
        uint8_t *ptr1 = *((uint8_t **) (arg0 + sizeof(void*)));
        for (size_t i2 = 0; i2 < len0; i2++) {
          uint8_t *base = ptr1 + i2 * (7*sizeof(void*));
          (void) base;
          if ((*((size_t*) (base + sizeof(void*)))) > 0) {
            free(*((uint8_t **) (base + 0)));
          }
          if ((*((size_t*) (base + (4*sizeof(void*))))) > 0) {
            free(*((uint8_t **) (base + (3*sizeof(void*)))));
          }
          size_t len = *((size_t*) (base + (6*sizeof(void*))));
          if (len > 0) {
            uint8_t *ptr = *((uint8_t **) (base + (5*sizeof(void*))));
            for (size_t i = 0; i < len; i++) {
              uint8_t *base = ptr + i * (4*sizeof(void*));
              (void) base;
              if ((*((size_t*) (base + sizeof(void*)))) > 0) {
                free(*((uint8_t **) (base + 0)));
              }
              if ((*((size_t*) (base + (3*sizeof(void*))))) > 0) {
                free(*((uint8_t **) (base + (2*sizeof(void*)))));
              }
            }
            free(ptr);
          }
        }
        free(ptr1);
      }
      break;
    }
    case 1: {
      switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + sizeof(void*)))) {
        case 0: {
          if ((*((size_t*) (arg0 + (3*sizeof(void*))))) > 0) {
            free(*((uint8_t **) (arg0 + (2*sizeof(void*)))));
          }
          break;
        }
        case 1: {
          break;
        }
        case 2: {
          break;
        }
      }
      break;
    }
  }
}


// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(4*sizeof(void*))];

// Helper Functions

void parser_plugin_tuple2_string_string_free(parser_plugin_tuple2_string_string_t *ptr) {
  parser_plugin_string_free(&ptr->f0);
  parser_plugin_string_free(&ptr->f1);
}

void parser_plugin_list_tuple2_string_string_free(parser_plugin_list_tuple2_string_string_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    parser_plugin_tuple2_string_string_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      parser_plugin_tuple2_string_string_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void local_log_process_parse_process_log_entry_free(local_log_process_parse_process_log_entry_t *ptr) {
  parser_plugin_string_free(&ptr->timestamp);
  parser_plugin_string_free(&ptr->message);
  parser_plugin_list_tuple2_string_string_free(&ptr->tags);
}

void local_log_process_parse_process_parse_error_free(local_log_process_parse_process_parse_error_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      parser_plugin_string_free(&ptr->val.invalid_format);
      break;
    }
    case 1: {
      break;
    }
  }
}

void parser_plugin_log_entry_free(parser_plugin_log_entry_t *ptr) {
  local_log_process_parse_process_log_entry_free(ptr);
}

void parser_plugin_parse_error_free(parser_plugin_parse_error_t *ptr) {
  local_log_process_parse_process_parse_error_free(ptr);
}

void parser_plugin_list_u8_free(parser_plugin_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void parser_plugin_list_list_u8_free(parser_plugin_list_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    parser_plugin_list_u8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      parser_plugin_list_u8_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void parser_plugin_list_log_entry_free(parser_plugin_list_log_entry_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    parser_plugin_log_entry_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      parser_plugin_log_entry_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void parser_plugin_result_list_log_entry_parse_error_free(parser_plugin_result_list_log_entry_parse_error_t *ptr) {
  if (!ptr->is_err) {
    parser_plugin_list_log_entry_free(&ptr->val.ok);
  } else {
    parser_plugin_parse_error_free(&ptr->val.err);
  }
}

void parser_plugin_string_set(parser_plugin_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void parser_plugin_string_dup(parser_plugin_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void parser_plugin_string_dup_n(parser_plugin_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void parser_plugin_string_free(parser_plugin_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__export_name__("parse")))
uint8_t * __wasm_export_exports_parser_plugin_parse(uint8_t * arg, size_t arg0) {
  parser_plugin_list_list_u8_t arg1 = (parser_plugin_list_list_u8_t) { (parser_plugin_list_u8_t*)(arg), (arg0) };
  parser_plugin_result_list_log_entry_parse_error_t ret;
  parser_plugin_list_log_entry_t ok;
  parser_plugin_parse_error_t err;
  ret.is_err = !exports_parser_plugin_parse(&arg1, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const parser_plugin_parse_error_t *payload2 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    switch ((int32_t) (*payload2).tag) {
      case 0: {
        const parser_plugin_string_t *payload3 = &(*payload2).val.invalid_format;
        *((int8_t*)(ptr + sizeof(void*))) = 0;
        *((size_t*)(ptr + (3*sizeof(void*)))) = (*payload3).len;
        *((uint8_t **)(ptr + (2*sizeof(void*)))) = (uint8_t *) (*payload3).ptr;
        break;
      }
      case 1: {
        const uint16_t *payload4 = &(*payload2).val.unsupported_version;
        *((int8_t*)(ptr + sizeof(void*))) = 1;
        *((int16_t*)(ptr + (2*sizeof(void*)))) = (int32_t) (*payload4);
        break;
      }
      case 2: {
        *((int8_t*)(ptr + sizeof(void*))) = 2;
        break;
      }
    }
  } else {
    const parser_plugin_list_log_entry_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload).ptr;
  }
  return ptr;
}

__attribute__((__export_name__("report-usage")))
int64_t __wasm_export_exports_parser_plugin_report_usage(void) {
  uint64_t ret = exports_parser_plugin_report_usage();
  return (int64_t) (ret);
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_parser_plugin(void);
__attribute__((used))
void __component_type_object_force_link_parser_plugin_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_parser_plugin();
}
