// Code generated by wit-bindgen-go. DO NOT EDIT.

package parserplugin

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "local:log-process/parser-plugin@0.1.0".
var Exports struct {
	// Parse represents the caller-defined, exported function "parse".
	//
	//	parse: func(raw-data: list<list<u8>>) -> result<list<parsed-entry>, parse-error>
	Parse func(rawData cm.List[cm.List[uint8]]) (result cm.Result[ParseErrorShape, cm.List[ParsedEntry], ParseError])

	// ReportUsage represents the caller-defined, exported function "report-usage".
	//
	//	report-usage: func() -> u64
	ReportUsage func() (result uint64)
}
