// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package parserplugin represents the world "local:log-process/parser-plugin@0.3.0".
//
// ─────────────────────────────────────────────
// parser-plugin
// 回傳 parsed-entry（無 id），host 統一分配 id 後轉為 log-entry
// ─────────────────────────────────────────────
package parserplugin

import (
	pipelineprocess "example.com/internal/local/log-process/pipeline-process"
)

// ParsedEntry represents the type alias "local:log-process/parser-plugin@0.3.0#parsed-entry".
//
// See [pipelineprocess.ParsedEntry] for more information.
type ParsedEntry = pipelineprocess.ParsedEntry

// ParseError represents the type alias "local:log-process/parser-plugin@0.3.0#parse-error".
//
// See [pipelineprocess.ParseError] for more information.
type ParseError = pipelineprocess.ParseError
